Repository acm-ucr/aurora, pull requests merged in 2023-11, with the labels that each got.

#856 simplify to filtered
  src/components/dynamic/admin/Table.jsx
Labels: Ready for Review

#857 changed if statement
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready for Review, Bug Fix, Dashboards

#840 added component testing??
  .github/workflows/pull-request.yaml
  cypress/component/Select.cy.jsx
  cypress/component/admin/Dropdown.cy.jsx
  cypress/component/admin/Filters.cy.jsx
  cypress/component/admin/Title.cy.jsx
  cypress/component/form/Button.cy.jsx
  cypress/fixtures/events.json
  src/components/dynamic/Select.jsx
Labels: Do Not Merge

#844 John/stretchtoolbar, issue 831
  src/app/admin/messenger/page.js
  src/components/dynamic/admin/Filters.jsx
  src/components/dynamic/admin/dashboards/Toolbar.jsx
  src/components/dynamic/admin/services/Messenger.jsx
Labels: Ready for Review

#784 restricts winner to qualify action and adds a popup
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready for Review

#780 need help with issue
  src/components/dynamic/admin/dashboards/Modal.jsx
Labels: Do Not Merge

#859 prevent deleting winners
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready to Merge

#847 judge affiliation to lower
  src/app/api/judges/route.js
  src/data/dynamic/Tags.js
Labels: Do Not Merge, Judges, Backend

#861 fix cron job
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#870 added stats loading anim
  src/components/dynamic/admin/services/statistics/Statistics.jsx
Labels: Ready for Review

#854 added arrow key shortcuts
  src/components/dynamic/admin/services/calendar/Toolbar.jsx
Labels: Ready for Review, Calendar

#874 fixed made
  src/app/layout.js
  src/components/dynamic/ProtectedPage.jsx
  src/data/ProtectedRoutes.js
Labels: Ready to Merge

#875 Fuyuki/disable-reset-button
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready to Merge

#863 AgentEinstein/add error checking
  src/components/dynamic/user/Team.jsx
Labels: User Portal, Ready to Merge

#889 format diet string[] as string
  src/app/api/participants/route.js
Labels: Participants, Ready for Review, Backend

#899 Toolbar tests
  cypress/component/admin/dashboards/Toolbar.cy.jsx
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Tests

#915 fixed cron job date
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#919 added github token to cronjob
  .github/workflows/sync-template.yaml
Labels: Repository

#921 added default location
  src/components/dynamic/admin/services/calendar/Modal.jsx
Labels: Ready for Review

#914 fix dropdown
  cypress/component/admin/Dropdown.cy.jsx
  src/app/api/prizes/route.js
  src/components/dynamic/Select.jsx
  src/components/dynamic/admin/services/DropDown.jsx
  src/components/dynamic/admin/services/Dropdown.jsx
  src/components/dynamic/admin/services/Toolbar.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/form/Questions.jsx
Labels: Ready for Review

#922 add discord
  cypress/e2e/admin/participants/Sort.cy.js
  cypress/fixtures/participants.json
  src/app/api/participants/route.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Volunteers.js
Labels: Participants, Ready to Merge
