Repository acm-ucr/aurora, pull requests merged in 2023-10, with the labels that each got.

#697 Seanquiambao/readme
  README.md
Labels: Repository, Ready to Merge

#689 input component tests
  cypress/component/Input.cy.jsx
  src/components/Input.jsx
Labels: Ready for Review, Raidah F., Tests

#734 add date
  src/data/Config.js
Labels: Ready to Merge

#746 fix calendar
  src/components/admin/services/calendar/Events.jsx
Labels: Ready to Merge

#761 add discord column to admin and committees
  src/app/api/admins/route.js
  src/app/api/committees/route.js
  src/data/admin/Admins.js
  src/data/admin/Committees.js
Labels: Admin, Ready to Merge, Committee

#770 Jonathan/switch bars
  src/components/dynamic/admin/services/Toolbar.jsx
Labels: Ready to Merge

#767 resized button
  src/components/dynamic/admin/Button.jsx
Labels: Do Not Merge

#763 fix team error
  src/app/api/members/route.js
  src/app/api/team/route.js
Labels: Do Not Merge

#769 Fix Form Bug
  src/components/dynamic/forms/Form.jsx
Labels: Bug Fix, Ready to Merge

#772 added logo
  public/UCRLOGO.png
  src/components/dynamic/Navigation.jsx
Labels: Ready to Merge

#777 Add GCP Deployment Files
  Dockerfile
  cloudbuild.yaml
  package.json
Labels: Ready to Merge

#771 Shahdivyank/stats
  package-lock.json
  package.json
  src/app/admins/statistics/page.js
  src/app/api/messenger/route.js
  src/app/api/statistics/route.js
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/admin/Title.jsx
  src/components/dynamic/admin/services/Messenger.jsx
  src/components/dynamic/admin/services/PieChart.jsx
  src/components/dynamic/admin/services/Statistics.jsx
  src/components/dynamic/admin/services/statistics/Statistics.jsx
  src/components/dynamic/admin/services/statistics/Tab.jsx
  src/components/dynamic/admin/services/statistics/Tabs.jsx
  src/data/Config.js
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Feedback.js
Labels: Statistics

#773 fix teams api
  src/app/api/members/route.js
  src/app/api/participant/route.js
  src/app/api/team/route.js
  src/app/api/teams/route.js
  src/app/users/join/[teamID]/page.js
  src/components/dynamic/user/Team.jsx
Labels: Ready to Merge

#766 Added status column
  src/app/api/prizes/route.js
  src/components/dynamic/admin/services/Prizes.jsx
  src/components/dynamic/admin/services/Toolbar.jsx
  src/data/dynamic/admin/Prizes.js
Labels: Ready to Merge

#776 Add feedback form to user portal
  src/data/dynamic/Navigation.js
Labels: Navigation, User Portal, Ready to Merge, Feedback

#782 added terms and conditions header to all forms
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Judge.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Volunteers.js
Labels: Ready to Merge, Forms

#781 Padam11/fix tag order
  src/app/api/members/route.js
  src/app/api/participant/route.js
  src/app/users/checkin/page.js
  src/app/users/dashboard/page.js
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Prizes.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready to Merge, Dashboards

#765 Added Operations
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
Labels: Ready to Merge

#779 Add robots.txt
  src/app/robots.txt
Labels: Repository, Ready to Merge

#774 Menthy/form
  cypress/component/Input.cy.jsx
  cypress/component/forms/Upload.cy.jsx
  src/app/api/committees/route.js
  src/app/api/judges/route.js
  src/app/api/judging/route.js
  src/app/api/members/route.js
  src/app/api/mentors/route.js
  src/app/api/participant/route.js
  src/app/api/participants/route.js
  src/app/api/team/route.js
  src/app/api/teams/route.js
  src/app/api/volunteers/route.js
  src/app/users/checkin/page.js
  src/components/dynamic/forms/Admin.jsx
  src/components/dynamic/forms/Committee.jsx
  src/components/dynamic/forms/Feedback.jsx
  src/components/dynamic/forms/Judge.jsx
  src/components/dynamic/forms/Mentor.jsx
  src/components/dynamic/forms/Participant.jsx
  src/components/dynamic/forms/Volunteer.jsx
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Availability.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Feedback.js
  src/data/dynamic/forms/Judge.js
  src/data/dynamic/forms/Judges.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/User.js
  src/data/dynamic/forms/Volunteers.js
  src/data/dynamic/user/Members.js
  src/data/dynamic/user/Participant.js
  src/data/dynamic/user/Team.js
Labels: Ready to Merge

#787 fix select
  src/components/dynamic/Select.jsx
Labels: Ready to Merge

#788 Victor/reload style
  src/components/dynamic/admin/dashboards/Toolbar.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Bug Fix, Admin, Ready to Merge

#786 Added Spacing Between Buttons
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Judging, Ready to Merge

#790 fix diet requrie
  src/data/dynamic/forms/Participant.js
Labels: Ready to Merge

#792 added reload icon
  src/components/dynamic/admin/services/Toolbar.jsx
Labels: Ready to Merge, Prizes

#799 get rid of bootstrap grid
  src/components/dynamic/Radio.jsx
  src/components/dynamic/admin/Filters.jsx
  src/components/dynamic/admin/Table.jsx
  src/components/dynamic/admin/dashboards/SortIcon.jsx
  src/components/dynamic/admin/services/Upload.jsx
  src/components/dynamic/admin/services/calendar/Toolbar.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/admin/services/checkin/Scanner.jsx
  src/components/dynamic/admin/services/judging/Table.jsx
  src/components/dynamic/admin/services/statistics/Tab.jsx
  src/components/dynamic/admin/services/statistics/Tabs.jsx
  src/components/dynamic/forms/Form.jsx
  src/components/dynamic/forms/Participant.jsx
  src/components/dynamic/user/Dashboard.jsx
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready to Merge

#796 Add Toast HandleReload
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready to Merge

#800 update resume
  src/app/api/participants/route.js
  src/components/dynamic/admin/Table.jsx
Labels: Ready to Merge

#809 fix title
  src/components/dynamic/admin/Title.jsx
  src/components/dynamic/admin/services/statistics/Tab.jsx
Labels: Ready to Merge

#808 fix diet to array
  src/app/api/participant/route.js
  src/components/dynamic/user/Dashboard.jsx
  src/components/dynamic/user/User.jsx
Labels: Ready to Merge

#811 added filter to links in teams api
  src/app/api/teams/route.js
Labels: Teams, Ready to Merge, Backend

#807 fix nav
  src/components/dynamic/Navigation.jsx
  src/data/dynamic/Navigation.js
Labels: Ready for Review

#810 fix form
  src/components/dynamic/forms/Form.jsx
  src/components/dynamic/forms/Judge.jsx
  src/components/dynamic/forms/Mentor.jsx
  src/components/dynamic/forms/Participant.jsx
  src/components/dynamic/forms/Volunteer.jsx
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Judge.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Volunteers.js
Labels: Ready for Review

#815 remove availability
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Volunteers.js
  src/data/dynamic/forms/Availability.js
  src/data/dynamic/forms/Information.js
Labels: Ready for Review

#688 struggling to make the the search bar :////
  src/components/dynamic/Select.jsx
  src/components/dynamic/forms/Form.jsx
  src/data/dynamic/forms/Information.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Schools.js
Labels: Ready for Review, Register

#814 Update Navigation.jsx
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/ProtectedPage.jsx
  src/data/dynamic/Navigation.js
Labels: Ready for Review

#816 change options to items
  src/components/dynamic/user/User.jsx
Labels: Ready for Review

#775 Create Dashboard Wrapper
  cypress/e2e/admins/admins/Search.cy.js
  src/components/dynamic/admin/Dashboard.jsx
  src/components/dynamic/admin/dashboards/Admins.jsx
  src/components/dynamic/admin/dashboards/Committees.jsx
  src/components/dynamic/admin/dashboards/Judges.jsx
  src/components/dynamic/admin/dashboards/Mentors.jsx
  src/components/dynamic/admin/dashboards/Participants.jsx
  src/components/dynamic/admin/dashboards/Teams.jsx
  src/components/dynamic/admin/dashboards/Volunteers.jsx
Labels: Ready for Review, Dashboards

#812 fix alignment
  src/components/dynamic/admin/Table.jsx
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready for Review

#795 Jonathan/add empty message
  src/components/dynamic/admin/services/DropDown.jsx
  src/components/dynamic/admin/services/Toolbar.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
Labels: Ready for Review

#819 Forms
  cypress/fixtures/admins.json
  cypress/fixtures/committees.json
  src/components/dynamic/forms/Form.jsx
  src/data/dynamic/Tags.js
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Information.js
  src/data/dynamic/forms/Judge.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Volunteers.js
Labels: Ready to Merge

#820 added calendar shortcuts
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: Ready for Review

#842 removed GCP deployment files
  Dockerfile
  cloudbuild.yaml
  package.json
Labels: Repository

#839 moved useState into dashboard
  src/components/dynamic/admin/Dashboard.jsx
  src/components/dynamic/admin/dashboards/Admins.jsx
  src/components/dynamic/admin/dashboards/Committees.jsx
  src/components/dynamic/admin/dashboards/Feedback.jsx
  src/components/dynamic/admin/dashboards/Judges.jsx
  src/components/dynamic/admin/dashboards/Mentors.jsx
  src/components/dynamic/admin/dashboards/Participants.jsx
  src/components/dynamic/admin/dashboards/Teams.jsx
  src/components/dynamic/admin/dashboards/Volunteers.jsx
Labels: Ready for Review, Dashboards

#837 added No Team Selected placeholder
  src/components/dynamic/admin/services/Prizes.jsx
Labels: Ready for Review, Prizes

#838 Agent einstein/successfully updated
  src/components/dynamic/user/Team.jsx
  src/components/dynamic/user/User.jsx
Labels: Bug Fix

#836 added sitemap.js
  src/app/sitemap.js
  src/data/Config.js
Labels: Ready for Review, Repository

#794 added only numbers function
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready for Review, Judging

#672 Select component test
  cypress/component/Select.cy.jsx
Labels: Ready for Review, Tests

#835 add return
  src/components/dynamic/form/Upload.jsx
Labels: Ready to Merge

#853 loading
  src/app/loading.js
Labels: Ready for Review, Admin

#850 added cronjob
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#849 moved 404 and 500 errors into error component
  src/app/error.js
  src/app/not-found.js
Labels: Ready for Review, Repository
