Repository acm-ucr/aurora, pull requests merged in 2023-08, with the labels that each got.

#160 fix judge
  src/components/Judge.jsx
  src/components/Judges.jsx
  src/components/Participant.jsx
  src/components/Participants.jsx
  src/components/Tag.jsx
  src/components/Team.jsx
  src/components/Teams.jsx
  src/components/Toolbar.jsx
  tailwind.config.js
Labels: Ready for Review, Judges

#166 fix all formatting BUGs for participants, teams, and judges
  src/components/Judge.jsx
  src/components/Judges.jsx
  src/components/Member.jsx
  src/components/Participant.jsx
  src/components/Participants.jsx
  src/components/SortIcon.jsx
  src/components/Tag.jsx
  src/components/Team.jsx
  src/components/Teams.jsx
Labels: Participants, Teams, Ready for Review, Bug Fix, Judges

#153 added FA download icon at the end of toolbar
  package-lock.json
  src/components/Toolbar.jsx
Labels: Ready for Review

#167 added volunteer and mentor pages and added the new icons. updated react-icons from 4.9.0 to 4.10.0 in package.json
  package-lock.json
  package.json
  src/app/admin/mentor/page.js
  src/app/admin/volunteer/page.js
  src/data/Navigation.js
Labels: Ready for Review

#202 used Title component
  src/app/user/checkin/page.js
  src/components/CheckIn.jsx
Labels: Ready for Review, User Portal

#203 changed the rejected tag color to red
  src/components/Participant.jsx
Labels: Ready for Review

#204 switched Winner and Pending colors
  src/components/Team.jsx
Labels: Ready for Review

#213 Volunteer Page
  src/app/admin/volunteer/page.js
  src/app/forms/volunteer/page.js
  src/components/Tag.jsx
  src/components/Volunteer.jsx
  src/components/Volunteers.jsx
Labels: Ready for Review, Volunteers

#210 added admissions page
  src/app/admin/admissions/page.js
  src/data/Navigation.js
Labels: Ready for Review

#209 added trash icon
  src/components/Toolbar.jsx
Labels: Ready for Review

#212 Mentor Page
  src/app/admin/mentor/page.js
  src/app/admin/mentors/page.js
  src/app/admin/volunteers/page.js
  src/app/forms/mentor/page.js
  src/components/Mentor.jsx
  src/components/Mentors.jsx
Labels: Ready for Review, Mentors

#215 Switched order of buttons on Judges page
  src/components/Judges.jsx
Labels: Ready for Review, Judges

#216 Switched order of buttons on Teams page
  src/components/Teams.jsx
Labels: Teams, Ready for Review

#182 Adding live timer for check-in page
  src/components/CheckIn.jsx
Labels: User Portal

#214 Placing statistics below mentor and "judging" to "judges"
  src/data/Navigation.js
Labels: Navigation

#217 Judging Page
  src/components/Judges.jsx
Labels: Ready for Review, Judges

#218 Admin Request Form
  src/app/forms/admin/page.js
  src/components/Admin.jsx
  src/components/Radio.jsx
Labels: Ready for Review

#220 Fix Website
  src/app/admin/judging/page.js
  src/app/admin/mentors/page.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/admin/volunteers/page.js
  src/app/forms/admin/page.js
  src/app/forms/mentor/page.js
  src/app/forms/register/page.js
  src/app/forms/volunteer/page.js
  src/app/user/checkin/page.js
  src/app/user/dashboard/page.js
  src/components/Admin/Filters.jsx
  src/components/Admin/Judge.jsx
  src/components/Admin/Judges.jsx
  src/components/Admin/Member.jsx
  src/components/Admin/Mentor.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Participant.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/PieChart.jsx
  src/components/Admin/SortIcon.jsx
  src/components/Admin/Tag.jsx
  src/components/Admin/Team.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Admin/Volunteer.jsx
  src/components/Admin/Volunteers.jsx
  src/components/Forms/Admin.jsx
  src/components/Forms/Mentor.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Upload.jsx
  src/components/Forms/Volunteer.jsx
  src/components/ProfileButton.jsx
  src/components/ProfileCard.jsx
  src/components/TeamCard.jsx
  src/components/User/CheckIn.jsx
  src/components/User/Dashboard.jsx
  src/components/User/Header.jsx
Labels: Bug Fix

#201 3x3 piechart
  src/app/admin/statistics/page.js
  src/components/Admin/PieChart.jsx
Labels: Statistics, Ready for Review

#223 admission
  src/app/admin/admissions/page.js
  src/components/Admin/Admissions.jsx
  src/components/ProtectedPage.jsx
Labels: Ready for Review, Admissions

#222 error message
  src/app/error.js
  src/components/Admin/Filters.jsx
Labels: Ready for Review, Bug Fix

#234 Messenger in Nav
  package-lock.json
  src/app/admin/statistics/page.js
  src/components/Admin/Admissions.jsx
  src/components/Admin/Judge.jsx
  src/components/Admin/Judges.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Title.jsx
  src/components/Admin/Volunteers.jsx
  src/components/Form.jsx
  src/components/Forms/Admin.jsx
  src/components/Forms/Button.jsx
  src/components/Forms/Mentor.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Text.jsx
  src/components/Forms/Volunteer.jsx
  src/components/User/CheckIn.jsx
  src/data/Navigation.js
Labels: Navigation

#225 make inputs components
  src/components/Admin/Admissions.jsx
  src/components/BodyInput.jsx
  src/components/SubjectInput.jsx
Labels: Ready for Review, Admissions

#246 Pull session name, email, id, image
  next.config.js
  src/app/user/dashboard/page.js
  src/components/User/CheckIn.jsx
  src/components/User/Header.jsx
Labels: Ready for Review, User Portal

#269 add hover animation
  src/components/Admin/Filters.jsx
  src/components/Admin/Toolbar.jsx
Labels: Ready for Review

#270 changed pending colors from yellow to gray on judges page
  src/components/Admin/Judge.jsx
  src/components/Admin/Judges.jsx
Labels: Judges

#273 fixed highlight border radius
  src/components/Admin/Judge.jsx
  src/components/Admin/Mentor.jsx
  src/components/Admin/Team.jsx
  src/components/Admin/Volunteer.jsx
Labels: Teams, Ready for Review, Bug Fix

#272 Moved data array
  src/app/admin/statistics/page.js
  src/components/Admin/PieChart.jsx
Labels: Statistics, Ready for Review

#276 fixed judge type colors
  src/components/Admin/Tag.jsx
Labels: Judges

#279 replaced old button with new button in judges
  src/components/Admin/Button.jsx
  src/components/Admin/Judges.jsx
Labels: Ready for Review, Judges

#271 Seanquiambao/admin page
  src/app/admin/admin/page.js
  src/components/Admin/Admin.jsx
  src/components/Admin/Admins.jsx
Labels: Ready for Review, Admin

#280 changed default
  src/components/Admin/Admissions.jsx
Labels: Ready for Review

#281 Admin Enable + Tag Fix
  src/app/admin/statistics/page.js
  src/components/Admin/Toolbar.jsx
  src/components/Label.jsx
  src/components/LoginButton.jsx
  src/data/Navigation.js
Labels: Ready for Review

#282 Fix Judges Not Attending
  src/components/Admin/Judge.jsx
  src/components/Admin/Judges.jsx
Labels: Ready for Review, Judges

#283 Moved add judge to top
  src/components/Admin/Judges.jsx
Labels: Ready for Review, Judges

#274 checkt recipient
  src/components/Admin/Admissions.jsx
Labels: Ready for Review

#287 Fixed accordion dropdown
  src/components/Admin/Participant.jsx
Labels: Participants, Ready for Review

#284 Menthy/table
  src/app/admin/admin/page.js
  src/app/admin/admissions/page.js
  src/app/admin/judging/page.js
  src/app/admin/mentors/page.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/admin/volunteers/page.js
  src/app/user/checkin/page.js
  src/components/Admin/Admin.jsx
  src/components/Admin/Admins.jsx
  src/components/Admin/Admissions.jsx
  src/components/Admin/Filters.jsx
  src/components/Admin/Judge.jsx
  src/components/Admin/Judges.jsx
  src/components/Admin/Mentor.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Participant.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/SortIcon.jsx
  src/components/Admin/Statistics.jsx
  src/components/Admin/Table.jsx
  src/components/Admin/Tag.jsx
  src/components/Admin/Team.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Admin/Volunteer.jsx
  src/components/Admin/Volunteers.jsx
  src/components/Checkbox.jsx
  src/components/ProtectedPage.jsx
  src/data/Filters.js
  src/data/Headers.js
  src/data/Tags.js
  src/data/mock/PieCharts.js
  src/data/mock/TableData.js
Labels: Ready for Review

#267 added messenger page and front-end elements
  src/app/admin/messenger/page.js
  src/components/Admin/Messenger.jsx
  src/data/Navigation.js
  tailwind.config.js
Labels: Ready for Review

#308 Changed judge type color names
  src/components/Admin/Tag.jsx
  src/data/Tags.js
  tailwind.config.js
Labels: Ready for Review, Bug Fix, Judges

#311 Removed highlight on admissions and messenger page
  src/components/Admin/Input.jsx
Labels: Messenger, Admissions, Admin

#310 Fixes
  firebase.js
  src/components/Admin/Messenger.jsx
  src/components/Admin/SortIcon.jsx
  src/components/Admin/Table.jsx
  src/components/Admin/Toolbar.jsx
  src/data/Headers.js
  src/data/Navigation.js
Labels: Ready for Review

#312 Error Pages
  src/app/error.js
  src/app/not-found.js
Labels: Ready for Review

#313 Update page.js
  src/app/admin/admin/page.js
Labels: Admin

#315 delete functionality and reset
  src/components/Admin/Toolbar.jsx
Labels: Ready for Review

#317 fix filter,toolbar
  src/components/Admin/Tag.jsx
  src/components/Forms/Admin.jsx
  src/data/AdminForm.js
  src/data/Filters.js
  src/data/Headers.js
  src/data/Tags.js
  src/data/mock/admin.js
  src/data/mock/participants.js
  tailwind.config.js
Labels: Ready for Review

#319 form scroll
  src/app/forms/admin/page.js
  src/app/forms/judge/page.js
  src/app/forms/mentor/page.js
  src/app/forms/register/page.js
  src/app/forms/volunteer/page.js
  src/components/Form.jsx
Labels: Ready for Review

#314 Reconfigure Navigation
  src/app/admin/admissions/page.js
  src/components/Admin/Admissions.jsx
  src/components/Navigation.jsx
  src/data/Navigation.js
Labels: Ready for Review

#350 removed highlight
  src/components/Admin/Textarea.jsx
Labels: Admissions, Admin

#351 Add lead position and winner icon for teams and admin
  src/components/Admin/Table.jsx
  src/data/Headers.js
  src/data/mock/admin.js
Labels: Teams, Admin

#320 create admin checkin page
  package-lock.json
  package.json
  src/app/admin/checkin/page.js
  src/components/Admin/CheckIn.jsx
  src/components/Admin/CheckInfo.jsx
  src/components/Admin/DropDown.jsx
  src/components/Admin/ScanQRCode.jsx
  src/components/Admin/Tag.jsx
  src/data/mock/checkInUser.js
  src/data/mock/events.js
Labels: Ready for Review, Check In

#356 Change tagColor to colors
  src/components/Admin/Table.jsx
  src/components/Admin/Toolbar.jsx
  src/data/Tags.js
Labels: Ready for Review, Repository

#357 Make navigation text size slightly larger
  src/components/Navigation.jsx
Labels: Navigation, Ready for Review

#352 fix spacing
  src/components/Navigation.jsx
  src/data/Navigation.js
Labels: Ready for Review

#354 Calendar Page
  package-lock.json
  package.json
  src/app/admin/calendar/page.js
  src/components/Admin/Calendar/Event.jsx
  src/components/Admin/Calendar/Events.jsx
  src/components/Admin/Calendar/Modal.jsx
  src/components/Admin/Calendar/Toolbar.jsx
  src/components/Admin/SortIcon.jsx
  src/components/Admin/Tag.jsx
  src/data/Calendar.js
  src/data/Navigation.js
Labels: Ready for Review, Calendar

#353 maxLength to inputs
  src/components/Admin/Input.jsx
  src/components/Forms/Admin.jsx
  src/components/Forms/Feedback.jsx
  src/components/Forms/Judge.jsx
  src/components/Forms/Mentor.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Volunteer.jsx
  src/components/Input.jsx
Labels: Register, Volunteers, Mentors

#369 add availabilities
  src/components/Forms/Mentor.jsx
  src/components/Forms/Volunteer.jsx
  src/data/Register.js
Labels: Volunteers, Mentors

#371 updated src/data/mock files with more user data except pieCharts
  src/data/mock/admin.js
  src/data/mock/judges.js
  src/data/mock/mentors.js
  src/data/mock/participants.js
  src/data/mock/teams.js
  src/data/mock/volunteers.js
Labels: Ready for Review

#375 Update Navigation.js
  src/data/Navigation.js
Labels: Navigation

#378 Consolidate Edit Icons
  src/components/Input.jsx
  src/components/Radio.jsx
  src/components/Select.jsx
  src/components/User/Dashboard.jsx
Labels: User Portal

#376 add popup
  src/components/Admin/Button.jsx
  src/components/Admin/Popup.jsx
  src/components/Admin/Toolbar.jsx
  src/data/admin/buttonColor.js
Labels: Ready for Review

#368 Extracted volunteer desccription and requirements
  src/components/Forms/Volunteer.jsx
  src/data/Volunteers.js
Labels: Ready for Review, Volunteers

#370 Variable rename to requirement
  src/components/Forms/Admin.jsx
  src/data/AdminForm.js
Labels: Admin

#374 add image colum
  src/components/Admin/Table.jsx
  src/data/Headers.js
  src/data/Tags.js
  src/data/mock/judges.js
Labels: Ready for Review

#377 Menthy/upload
  src/components/Forms/Judge.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Upload.jsx
Labels: Ready for Review

#396 Twang0323/add following affiliations
  src/data/AdminForm.js
  src/data/Tags.js
  src/data/mock/admin.js
  src/data/mock/participants.js
Labels: Ready for Review

#367 attatchement and fix checkin
  src/app/admin/messenger/page.js
  src/components/Admin/CheckIn.jsx
  src/components/Admin/CheckInfo.jsx
  src/components/Admin/DropDown.jsx
  src/components/Admin/Input.jsx
  src/components/Admin/Messenger.jsx
  src/components/Admin/ScanQRCode.jsx
  src/components/Admin/Textarea.jsx
  src/components/Admin/Upload.jsx
  src/components/Forms/Upload.jsx
  src/data/Filters.js
  src/data/bytes.js
  src/data/mock/events.js
Labels: Ready for Review

#380 AgentEinstein/remove react imports
  src/app/admin/admin/page.js
  src/app/admin/calendar/page.js
  src/app/admin/checkin/page.js
  src/app/admin/judging/page.js
  src/app/admin/mentors/page.js
  src/app/admin/messenger/page.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/admin/volunteers/page.js
  src/app/forms/admin/page.js
  src/app/forms/judge/page.js
  src/app/forms/mentor/page.js
  src/app/forms/register/page.js
  src/app/forms/volunteer/page.js
  src/app/not-found.js
  src/app/user/checkin/page.js
  src/app/user/dashboard/page.js
  src/components/Admin/Admins.jsx
  src/components/Admin/Button.jsx
  src/components/Admin/CheckIn.jsx
  src/components/Admin/CheckInfo.jsx
  src/components/Admin/DropDown.jsx
  src/components/Admin/Filters.jsx
  src/components/Admin/Input.jsx
  src/components/Admin/Judges.jsx
  src/components/Admin/Member.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Messenger.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/Popup.jsx
  src/components/Admin/ScanQRCode.jsx
  src/components/Admin/SortIcon.jsx
  src/components/Admin/Statistics.jsx
  src/components/Admin/Table.jsx
  src/components/Admin/Tag.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Textarea.jsx
  src/components/Admin/Title.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Admin/Volunteers.jsx
  src/components/Checkbox.jsx
  src/components/Forms/Admin.jsx
  src/components/Forms/Feedback.jsx
  src/components/Forms/Judge.jsx
  src/components/Forms/Mentor.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Upload.jsx
  src/components/Forms/Volunteer.jsx
  src/components/LoginButton.jsx
  src/components/Navigation.jsx
  src/components/Radio.jsx
  src/components/Select.jsx
  src/components/User/Dashboard.jsx
  src/components/User/Header.jsx
Labels: Ready for Review, Repository

#400 Added scroll for dropdown
  src/components/Forms/Register.jsx
  src/components/Select.jsx
Labels: Ready for Review, Register

#394 fix hover
  src/components/Admin/Tag.jsx
Labels: Ready for Review

#401 Export Tag Colors
  src/components/Admin/Tag.jsx
  src/data/TagColors.js
Labels: Ready for Review

#399 Aditithanekar/default acceptance message
  src/components/Admin/Messenger.jsx
  src/components/Admin/Textarea.jsx
Labels: Ready for Review, Messenger, Shing H.

#404 add data folder
  tailwind.config.js
Labels: Ready for Review, Bug Fix

#405 Changed stats tags to green
  src/components/Admin/Statistics.jsx
Labels: Statistics, Ready for Review

#402 Fixed Default Edit
  src/components/Forms/Register.jsx
  src/components/Input.jsx
  src/components/Radio.jsx
  src/components/Select.jsx
Labels: Ready for Review, Bug Fix, User Portal

#407 changed to adminrequest
  src/components/Forms/Admin.jsx
  src/data/AdminRequest.js
  src/data/hackathon-website.code-workspace
Labels: Ready for Review, Admin, Shing H.

#418 added email sort for mentors
  src/data/Headers.js
Labels: Ready for Review, Mentors, Shing H.

#417 email sorting for admin dropdown
  src/data/Headers.js
Labels: Ready for Review, Admin, Shing H.

#416 email sorting for volunteers
  src/data/Headers.js
Labels: Ready for Review, Volunteers, Shing H.

#411 added team names, sorting is working
  src/data/mock/participants.js
Labels: Participants, Ready for Review, Raidah F.

#415 email sort for header of judges
  src/data/Headers.js
Labels: Ready for Review, Judges, Shing H.

#414 changed email col to have sorting for participants
  src/data/Headers.js
Labels: Participants, Ready for Review, Shing H.

#413 changed title to judges
  src/app/admin/judges/page.js
  src/data/AdminForm.js
  src/data/Navigation.js
Labels: Judges

#412 Updated version of d3-color to resolve vulnerabilities
  package-lock.json
Labels: Ready for Review, Repository

#420 updated React Bootstrap
  src/components/Admin/CheckIn.jsx
  src/components/Admin/Filters.jsx
  src/components/Admin/Statistics.jsx
  src/components/Admin/Table.jsx
  src/components/Forms/Admin.jsx
  src/components/Forms/Feedback.jsx
  src/components/Forms/Judge.jsx
  src/components/Forms/Mentor.jsx
  src/components/Forms/Register.jsx
  src/components/Forms/Volunteer.jsx
  src/components/User/Dashboard.jsx
Labels: Repository, Menthy W.

#419 added position options
  src/components/Forms/Admin.jsx
  src/data/AdminRequest.js
Labels: Admin

#406 QR code Timestamp
  src/components/User/CheckIn.jsx
Labels: Ready for Review, Check In

#422 moved major, grade, and school to their own lines
  src/components/Forms/Register.jsx
Labels: Ready for Review, Register, Raidah F.

#421 Fix Tags
  src/components/Admin/Table.jsx
  src/data/hackathon-website.code-workspace
Labels: Ready for Review, Bug Fix

#427 Short URL
  src/components/Admin/Table.jsx
Labels: Ready for Review, Bug Fix, Menthy W.

#424 Remove Tag Default Color
  src/components/Admin/Tag.jsx
Labels: Ready for Review, Bug Fix, Menthy W.

#431 fix header
  src/data/Headers.js
Labels: Ready for Review

#409 adding proper affiliations to the calender in the admin page
  src/data/Calendar.js
  src/data/Register.jsx
Labels: Ready for Review, Menthy W.

#436 fixed button
  src/components/Admin/Toolbar.jsx
Labels: Participants
