Repository acm-ucr/aurora, pull requests merged in 2023-07, with the labels that each got.

#7 Setup Repo
  .github/workflows/pull-request.yaml
  src/app/layout.js
  tailwind.config.js
Labels: Ready for Review

#8 Teams Component
  src/app/components/Member.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
Labels: Teams, Ready for Review

#10 Skeleton for Participants
  src/app/admin/participants/page.js
  src/app/admin/teams/page.js
  src/app/components/Participants.jsx
  src/app/layout.js
  tailwind.config.js
Labels: Participants, Ready for Review

#18 Filtering
  src/app/admin/participants/page.js
  src/app/admin/teams/page.js
  src/app/components/Filter.jsx
  src/app/components/Filters.jsx
  src/app/components/Participants.jsx
  src/app/components/SortIcon.jsx
  tailwind.config.js
Labels: Participants, Ready for Review

#23 Menthy/nav
  public/LOGO.png
  src/app/components/Navigation.jsx
  src/app/layout.js
Labels: Ready for Review

#17 Fix all bugs and add github/devpost link and Title
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/components/Member.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
  src/app/components/Title.jsx
Labels: Teams, Ready for Review, Bug Fix

#30 Teams Filtering + Sorting
  src/app/admin/teams/page.js
  src/app/components/Filters.jsx
  src/app/components/Navigation.jsx
  src/app/components/Participants.jsx
  src/app/components/SortIcon.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
Labels: Teams

#29 pass in props to create tag
  src/app/components/Tag.jsx
Labels: Participants, Teams, Statistics, Ready for Review

#28 checkbox
  src/app/components/Checkbox.jsx
  src/app/components/Participants.jsx
Labels: Ready for Review

#32 Fix Filtering + Sorting Integrations
  src/app/components/Participants.jsx
  src/app/components/Tag.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
  tailwind.config.js
Labels: Participants, Teams, Ready for Review

#31 Fix Navigation
  src/app/components/Navigation.jsx
Labels: Navigation, Ready for Review, Bug Fix

#35 Fix Checkbox
  package-lock.json
  package.json
  src/app/components/Checkbox.jsx
  src/app/components/Filters.jsx
  src/app/components/Participants.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
Labels: Participants, Bug Fix

#40 fix Navigation highlight
  src/app/components/Filters.jsx
  src/app/components/Navigation.jsx
Labels: Navigation, Ready for Review, Bug Fix

#41 Fix Highlight
  src/app/components/Participant.jsx
  src/app/components/Participants.jsx
Labels: Participants, Bug Fix

#43 Safe duck/tool bar
  src/app/admin/participants/page.js
  src/app/admin/teams/page.js
  src/app/components/Toolbar.jsx
  src/app/page.js
Labels: Participants, Teams, Ready for Review

#45 Searching on Teams + Participants
  src/app/admin/participants/page.js
  src/app/admin/teams/page.js
  src/app/components/Filters.jsx
  src/app/components/Participants.jsx
  src/app/components/Tag.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
  src/app/components/Toolbar.jsx
Labels: Participants, Teams

#48 Checkbox Selection
  src/app/components/Checkbox.jsx
  src/app/components/Participant.jsx
  src/app/components/Participants.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
Labels: Participants, Teams, Ready for Review

#58 fix spacing, add title, add links header
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/components/Checkbox.jsx
  src/app/components/Member.jsx
  src/app/components/Participant.jsx
  src/app/components/Participants.jsx
  src/app/components/SortIcon.jsx
  src/app/components/Team.jsx
  src/app/components/Teams.jsx
Labels: Participants, Teams, Statistics, Ready for Review, Bug Fix

#73 Updates/Setup
  next.config.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/layout.js
  src/app/page.js
  src/app/register/page.js
  src/app/user/checkin/page.js
  src/app/user/dashboard/page.js
  src/components/Checkbox.jsx
  src/components/Filters.jsx
  src/components/Member.jsx
  src/components/Navigation.jsx
  src/components/Participant.jsx
  src/components/Participants.jsx
  src/components/SortIcon.jsx
  src/components/Tag.jsx
  src/components/Team.jsx
  src/components/Teams.jsx
  src/components/Title.jsx
  src/components/Toolbar.jsx
  src/data/Navigation.js
Labels: Participants, Ready for Review, Repository

#75 Register MiddleEnd
  src/app/register/page.js
  src/components/Checkbox.jsx
  src/components/Radio.jsx
  src/components/Register.jsx
  src/components/Select.jsx
  src/components/Upload.jsx
  src/data/Register.js
  src/data/Schools.js
  src/data/User.js
Labels: Ready for Review, Register

#77 Judging
  src/app/admin/judging/page.js
  src/components/Judging.jsx
  src/data/Navigation.js
Labels: Ready for Review, Judges

#79 Setup Stats
  package-lock.json
  package.json
  src/app/admin/statistics/page.js
  src/components/PieChart.jsx
Labels: Statistics, Ready for Review

#87 check in page
  package-lock.json
  package.json
  src/app/user/checkin/page.js
Labels: Ready for Review, User Portal

#88 Moved legend to right
  src/components/PieChart.jsx
Labels: Statistics, Ready for Review

#89 Removed Pie Filling Textures
  src/components/PieChart.jsx
Labels: Statistics, Ready for Review

#90 Removed Inbuilt margins
  src/components/PieChart.jsx
Labels: Statistics, Ready for Review

#93 added highlight function to selected checkboxes
  src/components/Participant.jsx
Labels: Ready for Review

#94 removed top border
  src/components/Participant.jsx
Labels: Ready for Review

#99 Fix Judging MiddleEnd
  src/components/Judging.jsx
Labels: Bug Fix, Judges

#115 fix participant/teams spacing
  src/components/Participants.jsx
  src/components/Tag.jsx
  src/components/Teams.jsx
  src/components/Title.jsx
  src/components/Toolbar.jsx
Labels: Participants, Teams, Ready for Review, Bug Fix

#116 Add Toasts
  package-lock.json
  package.json
  src/app/layout.js
  src/components/Judging.jsx
Labels: Ready for Review, Judges

#119 Event Key prop warning fix
  src/components/Participant.jsx
Labels: Ready for Review, Bug Fix

#121 changed data fields of pie chart with reject, accept, pending
  src/components/PieChart.jsx
Labels: Statistics

#122 Profile and Team Cards, Profile Buttons
  src/components/ProfileButton.jsx
  src/components/ProfileCard.jsx
  src/components/TeamCard.jsx
Labels: Ready for Review, User Portal

#123 judge add
  src/app/admin/judging/page.js
  src/components/Judge.jsx
  src/components/Judges.jsx
  tailwind.config.js
Labels: Ready for Review, Judges

#126 Profile header
  src/components/ProfileHeader.jsx
Labels: Ready for Review, User Portal

#125 Renamed Clear button to Reset, matched styling to pending button
  src/components/Toolbar.jsx
Labels: Ready for Review

#124 changed colors on pie chart to figma palette
  src/components/PieChart.jsx
Labels: Statistics

#127 Register form format
  src/components/Checkbox.jsx
  src/components/Radio.jsx
  src/components/Register.jsx
  src/components/Select.jsx
  src/components/Upload.jsx
  src/data/Register.js
Labels: Ready for Review, Register

#132 Judges Middle End
  src/app/admin/judging/page.js
  src/components/Judge.jsx
  src/components/Judges.jsx
  src/components/Toolbar.jsx
Labels: Ready for Review, Judges

#91 auth
  .github/workflows/pull-request.yaml
  firebase.js
  package-lock.json
  package.json
  src/app/admin/judging/page.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/api/auth/[...nextauth]/route.jsx
  src/app/error.js
  src/app/layout.js
  src/app/not-found.js
  src/app/page.js
  src/app/user/checkin/page.js
  src/app/user/dashboard/page.js
  src/components/Judging.jsx
  src/components/LoginButton.jsx
  src/components/ProtectedPage.jsx
Labels: Ready for Review

#149 Fixed hover bug (2nd attempt to push)
  src/components/Participant.jsx
  src/components/Tag.jsx
  src/components/Team.jsx
Labels: Participants, Teams, Ready for Review

#158 Removed whitespace at bottom of teams page
  src/components/Team.jsx
Labels: Teams, Ready for Review

#157 switched the Email and Type columns
  src/components/Judge.jsx
  src/components/Judges.jsx
Labels: Ready for Review

#156 added env, and changed title left padding
  package-lock.json
  src/components/Title.jsx
Labels: Participants, Teams

#155 added background color on selected rows
  src/components/Judge.jsx
Labels: Ready for Review

#154 Aligning Github/Devpost and Highlighting Teams Green
  src/components/Team.jsx
Labels: Ready for Review, Bug Fix
