Repository acm-ucr/aurora, pull requests merged in 2023-09, with the labels that each got.

#432 Add Cypress Testing
  .github/workflows/pull-request.yaml
  cypress.config.js
  cypress/component/Tag.cy.jsx
  cypress/e2e/AdminNavigation.cy.js
  cypress/e2e/AutoRedirects.cy.js
  cypress/fixtures/admin.json
  cypress/fixtures/user.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/components/Admin/Table.jsx
  src/components/Admin/Tag.jsx
  src/components/ProtectedPage.jsx
  src/data/TagColors.js
  src/data/Tags.js
Labels: Do Not Merge, Tests

#426 Add dietary restrictions to registration form
  src/components/Forms/Register.jsx
  src/data/Register.js
Labels: Ready for Review, Register

#430 fardinzam/Added loading page similar to 404/500 page
  src/components/Loading.jsx
  src/components/ProtectedPage.jsx
Labels: Ready for Review, Repository

#541 Package JSON Updates
  package-lock.json
  package.json
  src/data/Register.jsx
Labels: Ready for Review, Repository

#429 Add information to participant drop down
  src/components/Admin/Table.jsx
  src/data/Headers.js
  src/data/mock/participants.js
Labels: Participants, Ready for Review, Menthy W.

#425 create a register.jsx under the data folder to export register data
  src/components/Forms/Register.jsx
  src/data/Register.js
Labels: Ready for Review

#408 Changed accept and reject statuses to past tense
  src/components/Admin/Filters.jsx
  src/components/Admin/Table.jsx
Labels: Participants, Ready for Review

#542 changed filter texts/status tags
  src/data/Filters.js
  src/data/Tags.js
  src/data/mock/volunteers.js
Labels: Volunteers

#544 changed sentence of the max files to files instead of objects
  src/components/Admin/Upload.jsx
Labels: Messenger

#543 Tag Component Tests
  cypress/component/Tag.cy.jsx
  src/components/Admin/Tag.jsx
Labels: Ready for Review, Tests

#437 Disable drop drop menu when not in edit mode
  src/components/Select.jsx
Labels: Ready for Review, User Portal

#268 download csv file middle-end
  package-lock.json
  package.json
  src/components/Admin/Judges.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Admin/Volunteers.jsx
Labels: Participants, Teams, Ready for Review, Judges, Volunteers, Mentors

#546 fixed color issue on user dashboard
  src/components/User/Dashboard.jsx
Labels: Ready for Review, User Portal

#547 Textarea Component Tests
  cypress/component/Textarea.cy.jsx
  src/components/Admin/Textarea.jsx
Labels: Ready for Review, Tests

#557 reordered code
  src/components/Admin/DropDown.jsx
Labels: Raidah F.

#556 Changed labels
  src/data/mock/PieCharts.js
Labels: Raidah F.

#553 Change mentor form availability question to checkbox format
  src/components/Forms/Mentor.jsx
  src/components/Forms/Volunteer.jsx
  src/data/Register.js
Labels: Ready for Review, Volunteers, Mentors, Raidah F.

#554 Renamed data files to Pascal Case
  src/components/Admin/Admins.jsx
  src/components/Admin/Button.jsx
  src/components/Admin/CheckIn.jsx
  src/components/Admin/Judges.jsx
  src/components/Admin/Mentors.jsx
  src/components/Admin/Participants.jsx
  src/components/Admin/Teams.jsx
  src/components/Admin/Upload.jsx
  src/components/Admin/Volunteers.jsx
  src/components/Forms/Upload.jsx
  src/data/Bytes.js
  src/data/admin/ButtonColor.js
  src/data/mock/Admin.js
  src/data/mock/CheckInUser.js
  src/data/mock/Events.js
  src/data/mock/Judges.js
  src/data/mock/Mentors.js
  src/data/mock/Participants.js
  src/data/mock/Teams.js
  src/data/mock/Volunteers.js
Labels: Ready for Review, Data

#549 added pending action button for admin page
  src/data/Tags.js
Labels: Ready for Review, Admin

#562 removed the default selection in participants section
  src/data/mock/Participants.js
Labels: Ready for Review

#555 added pending to teams
  src/data/Tags.js
Labels: Teams

#434 Jonathan/tailwind colors
  src/components/Admin/Input.jsx
  src/components/Admin/Table.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Admin/Upload.jsx
  src/components/Checkbox.jsx
  src/components/Forms/Textarea.jsx
  src/components/Input.jsx
  src/components/Select.jsx
  tailwind.config.js
Labels: Ready for Review

#551 added judging
  src/app/admin/judging/page.js
  src/components/Admin/Judging.jsx
  src/data/Navigation.js
Labels: Ready for Review

#563 Changed tags to Pending, Confirm, Not Attending
  src/data/Tags.js
Labels: Ready for Review, Mentors

#548 admin action tests
  cypress/e2e/admin/Navigation.cy.js
  cypress/e2e/admin/admin/Actions.cy.js
  cypress/e2e/admin/admin/Filter.cy.js
  cypress/e2e/admin/admin/Search.cy.js
  cypress/e2e/admin/admin/Select.cy.js
  src/app/layout.js
  src/components/Admin/Button.jsx
  src/components/Admin/Filters.jsx
  src/components/Admin/Popup.jsx
  src/components/Admin/Table.jsx
  src/components/Admin/Toolbar.jsx
  src/components/Checkbox.jsx
Labels: Ready for Review

#552 added title to user dash board page
  src/components/User/Dashboard.jsx
Labels: Do Not Merge, User Portal

#545 fixed style of filter box
  src/components/Admin/DropDown.jsx
Labels: Check In

#569 mentor select
  cypress/e2e/admin/mentors/Select.cy.js
Labels: Ready for Review

#570 judges select
  cypress/e2e/admin/judges/Select.cy.js
Labels: Ready for Review

#571 team select
  cypress/e2e/admin/teams/Select.cy.js
Labels: Ready for Review

#572 participents select
  cypress/e2e/admin/participents/Select.cy.js
Labels: Ready for Review

#576 File Viewer
  src/components/Admin/Modal.jsx
  src/components/Admin/Table.jsx
  src/data/Headers.js
  src/data/mock/Participants.js
Labels: Ready for Review

#575 Fix Colors
  src/components/Admin/Calendar/Events.jsx
  src/components/Admin/Calendar/Modal.jsx
  src/components/Admin/Calendar/Toolbar.jsx
  src/data/Calendar.js
  src/data/Tags.js
  tailwind.config.js
Labels: Ready for Review, Calendar

#580 Judging Service
  cypress/component/Textarea.cy.jsx
  src/app/admin/admin/page.js
  src/app/admin/calendar/page.js
  src/app/admin/checkin/page.js
  src/app/admin/judges/page.js
  src/app/admin/judging/page.js
  src/app/admin/mentors/page.js
  src/app/admin/messenger/page.js
  src/app/admin/participants/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/admin/volunteers/page.js
  src/components/Admin/Button.jsx
  src/components/Admin/Dashboards/Admins.jsx
  src/components/Admin/Dashboards/Judges.jsx
  src/components/Admin/Dashboards/Mentors.jsx
  src/components/Admin/Dashboards/Modal.jsx
  src/components/Admin/Dashboards/Participants.jsx
  src/components/Admin/Dashboards/SortIcon.jsx
  src/components/Admin/Dashboards/Table.jsx
  src/components/Admin/Dashboards/Teams.jsx
  src/components/Admin/Dashboards/Toolbar.jsx
  src/components/Admin/Dashboards/Volunteers.jsx
  src/components/Admin/Judging.jsx
  src/components/Admin/Member.jsx
  src/components/Admin/Popup.jsx
  src/components/Admin/Services/Calendar/Event.jsx
  src/components/Admin/Services/Calendar/Events.jsx
  src/components/Admin/Services/Calendar/Modal.jsx
  src/components/Admin/Services/Calendar/Toolbar.jsx
  src/components/Admin/Services/CheckIn.jsx
  src/components/Admin/Services/CheckInfo.jsx
  src/components/Admin/Services/DropDown.jsx
  src/components/Admin/Services/Input.jsx
  src/components/Admin/Services/Judging.jsx
  src/components/Admin/Services/Messenger.jsx
  src/components/Admin/Services/PieChart.jsx
  src/components/Admin/Services/ScanQRCode.jsx
  src/components/Admin/Services/Statistics.jsx
  src/components/Admin/Services/Table.jsx
  src/components/Admin/Services/Textarea.jsx
  src/components/Admin/Services/Toolbar.jsx
  src/components/Admin/Services/Upload.jsx
  src/data/mock/Judging.js
Labels: Ready for Review, Judging

#573 fix loading width
  src/components/Loading.jsx
Labels: Ready to Merge

#561 Checkbox test - toggle off/on
  cypress/component/Checkbox.cy.jsx
  src/components/Checkbox.jsx
Labels: Tests, Ready to Merge

#587 Fix checkbox margin alignment
  src/components/Checkbox.jsx
Labels: Ready to Merge

#564 added toasts for incomplete fields for volunteers form
  src/components/Forms/Volunteer.jsx
  src/data/User.js
Labels: Volunteers, Shing H., Ready to Merge

#584 Popup Fixes
  src/components/Admin/Dashboards/Toolbar.jsx
  src/components/Admin/Popup.jsx
  src/components/Admin/Services/Toolbar.jsx
Labels: Ready to Merge

#590 Move mock data to cypress/fixtures, deleted mock data
  cypress/e2e/admin/admin/Actions.cy.js
  cypress/e2e/admin/admin/Filter.cy.js
  cypress/e2e/admin/admin/Search.cy.js
  cypress/e2e/admin/admin/Select.cy.js
  cypress/e2e/admin/judges/Select.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/participents/Select.cy.js
  cypress/e2e/admin/teams/Select.cy.js
  cypress/fixtures/Admin.json
  cypress/fixtures/CheckInUser.json
  cypress/fixtures/Events.json
  cypress/fixtures/JudgeList.json
  cypress/fixtures/Judges.json
  cypress/fixtures/Mentors.json
  cypress/fixtures/Participants.json
  cypress/fixtures/PieCharts.json
  cypress/fixtures/Teams.json
  cypress/fixtures/TeamsCopy.json
  cypress/fixtures/Volunteers.json
  src/components/Admin/Dashboards/Admins.jsx
  src/components/Admin/Dashboards/Judges.jsx
  src/components/Admin/Dashboards/Mentors.jsx
  src/components/Admin/Dashboards/Participants.jsx
  src/components/Admin/Dashboards/Teams.jsx
  src/components/Admin/Dashboards/Volunteers.jsx
  src/components/Admin/Services/CheckIn.jsx
  src/components/Admin/Services/Judging.jsx
  src/components/Admin/Services/Statistics.jsx
  src/data/mock/Admin.js
  src/data/mock/CheckInUser.js
  src/data/mock/Events.js
  src/data/mock/Judges.js
  src/data/mock/Judging.js
  src/data/mock/Mentors.js
  src/data/mock/Participants.js
  src/data/mock/PieCharts.js
  src/data/mock/Teams.js
  src/data/mock/Volunteers.js
Labels: Data, Ready to Merge

#592 Enable Sign Out
  cypress/fixtures/admin.json
  cypress/fixtures/admin_role.json
  cypress/fixtures/user_role.json
  cypress/support/commands.js
  src/components/Navigation.jsx
  src/data/Navigation.js
Labels: Ready to Merge

#593 Better Placeholder Hints
  src/components/Forms/Judge.jsx
Labels: Judges, Ready to Merge

#596 Toolbar Fixes
  src/components/Checkbox.jsx
Labels: Ready to Merge

#591 added toasts for incomplete fields on judges
  src/components/Forms/Judge.jsx
Labels: Judges, Shing H., Ready to Merge

#579 admin input comp test
  cypress/component/Input.cy.jsx
  src/components/Admin/Services/Input.jsx
Labels: Admin, Tests, Ready to Merge

#602 Prevent Duplicate Files
  src/components/Admin/Services/Upload.jsx
Labels: Messenger, Ready to Merge

#605 toast when qr is invalid, display no data
  src/components/Admin/Services/CheckInfo.jsx
Labels: Ready for Review, Check In

#604 Reset Toggle
  src/components/Admin/Dashboards/Toolbar.jsx
Labels: Ready to Merge

#603 Square Border
  src/components/Admin/Services/DropDown.jsx
Labels: Check In, Ready to Merge

#607 made upload icon smaller
  src/components/Forms/Upload.jsx
Labels: Register, Judges, Ready to Merge

#606 added toasts to user register form for field validation
  src/components/Forms/Register.jsx
  src/data/Forms/Information.js
  src/data/Forms/User.js
Labels: Register, Shing H., Ready to Merge

#609 Remove Reset Button
  src/components/Admin/Dashboards/Toolbar.jsx
Labels: Bug Fix, Ready to Merge

#610 Create Volunteers Filter Test
  cypress/e2e/admin/volunteers/Filter.cy.js
Labels: Volunteers, Raidah F., Tests

#608 e2e participants filtering
  cypress/e2e/admin/participents/Filter.cy.js
Labels: Ready for Review, Tests

#600 Mentors Actions E2E Test: aligned action buttons
  cypress/fixtures/Mentors.json
Labels: Do Not Merge

#599 E2E teams filters
  cypress/e2e/admin/teams/Filter.cy.js
  cypress/fixtures/Teams.json
Labels: Ready for Review, Tests

#598 comp test for admin filters
  cypress/component/Filters.cy.jsx
Labels: Ready for Review, Do Not Merge, Tests

#586 changed separate test names
  cypress/e2e/JudgeSearching.cy.js
  src/components/Admin/Dashboards/Toolbar.jsx
Labels: Ready for Review, Do Not Merge, Tests

#577 Created volunteers action test cases
  cypress/e2e/admin/volunteers/Actions.cy.js
Labels: Ready for Review, Do Not Merge, Tests

#565 Created test cases for volunteer searching
  cypress/e2e/admin/volunteers/Search.cy.js
Labels: Ready for Review, Do Not Merge, Tests

#566 Created test cases for participants search
  cypress/e2e/admin/participants/Search.cy.js
Labels: Do Not Merge, Tests

#567 mentor searching
  cypress/e2e/admin/mentors/Search.cy.js
Labels: Do Not Merge

#568 teams searching
  cypress/e2e/admin/teams/Search.cy.js
Labels: Ready for Review, Do Not Merge

#574 Added test cases for team actions
  cypress/e2e/admin/teams/Actions.cy.js
Labels: Do Not Merge, Tests

#612 Removed resize in text area
  src/components/Admin/Services/Textarea.jsx
Labels: Messenger, Ready to Merge

#611 Fixed padding toolbar search
  src/components/Admin/Dashboards/Toolbar.jsx
Labels: Ready for Review, Table, Ready to Merge

#620 file view fixes
  src/components/admin/dashboards/Modal.jsx
Labels: Participants, Judges, Divyank S., Ready to Merge

#601 added validation toasts on mentors form
  src/components/forms/Mentor.jsx
Labels: Mentors, Shing H., Ready to Merge

#558 fixed resize issue
  src/components/admin/dashboards/Judges.jsx
  src/components/forms/Mentor.jsx
  src/components/forms/Textarea.jsx
Labels: Mentors, Ready to Merge

#595 Anjaline/better icon
  src/components/forms/Upload.jsx
Labels: Register, Judges, Ready to Merge

#588 Button Component Testing
  cypress/component/forms/Button.cy.jsx
  src/components/Button.jsx
Labels: Ready to Merge

#621 Judge Testing
  cypress/e2e/admin/judges/Actions.cy.js
  cypress/e2e/admin/judges/Filter.cy.js
  cypress/e2e/admin/judges/Search.cy.js
  cypress/e2e/admin/judges/Select.cy.js
Labels: Ready to Merge

#618 added clear functionality
  .github/workflows/pull-request.yaml
  cypress/component/admin/Input.cy.jsx
  cypress/e2e/admin/admin/Search.cy.js
  cypress/e2e/admin/mentors/Search.cy.js
  cypress/e2e/admin/participants/Search.cy.js
  cypress/e2e/admin/teams/Search.cy.js
  cypress/e2e/admin/volunteers/Search.cy.js
  src/components/admin/Input.jsx
  src/components/admin/Popup.jsx
  src/components/admin/dashboards/Admins.jsx
  src/components/admin/dashboards/Judges.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/admin/dashboards/Teams.jsx
  src/components/admin/dashboards/Toolbar.jsx
  src/components/admin/dashboards/Volunteers.jsx
  src/components/admin/services/Messenger.jsx
  src/components/admin/services/Toolbar.jsx
  src/components/forms/Feedback.jsx
Labels: Participants, Teams, Judges, Volunteers, Mentors, Admin, Ready to Merge

#616 Sharan/title test2
  cypress/component/admin/Title.cy.jsx
  src/components/admin/Title.jsx
Labels: Raidah F., Tests, Ready to Merge

#626 feedback form page
  src/app/forms/feedback/page.js
  src/components/forms/Feedback.jsx
Labels: Ready to Merge, Feedback

#639 Prizes
  cypress/fixtures/prizes.json
  package-lock.json
  package.json
  src/app/admin/checkin/page.js
  src/app/admin/judging/page.js
  src/app/admin/prizes/page.js
  src/components/admin/Table.jsx
  src/components/admin/dashboards/Admins.jsx
  src/components/admin/dashboards/Judges.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/admin/dashboards/Teams.jsx
  src/components/admin/dashboards/Volunteers.jsx
  src/components/admin/services/Prizes.jsx
  src/components/admin/services/Toolbar.jsx
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/admin/services/checkin/CheckInfo.jsx
  src/components/admin/services/checkin/ScanQRCode.jsx
  src/components/admin/services/judging/Judging.jsx
  src/components/admin/services/judging/Table.jsx
  src/components/admin/services/judging/Toolbar.jsx
  src/data/Navigation.js
  src/data/admin/Prizes.js
Labels: Ready to Merge

#640 Display Availability on Mentors + Volunteers
  cypress/e2e/admin/mentors/Actions.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/volunteers/Actions.cy.js
  cypress/e2e/admin/volunteers/Select.cy.js
  cypress/fixtures/Mentors.json
  cypress/fixtures/Participants.json
  cypress/fixtures/Volunteers.json
  src/components/admin/Table.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/admin/dashboards/Volunteers.jsx
  src/data/admin/Mentors.js
  src/data/admin/Participants.js
  src/data/admin/Volunteers.js
  src/data/forms/Helper.js
Labels: Ready to Merge

#642 add cancel and placeholder
  src/components/admin/services/judging/Toolbar.jsx
Labels: Ready to Merge

#637 Forms Upload Component Testing
  cypress/component/forms/Upload.cy.jsx
  cypress/fixtures/files/sample.jpeg
  cypress/fixtures/files/sample.pdf
  cypress/fixtures/files/sample.png
  src/components/forms/Judge.jsx
  src/components/forms/Upload.jsx
  src/data/forms/Judges.js
Labels: Tests, Ready to Merge

#648 fix user dashbaord
  cypress/fixtures/User.json
Labels: Ready to Merge

#643 fix delete button
  src/components/admin/dashboards/Toolbar.jsx
Labels: Ready to Merge

#641 extract data
  src/components/admin/Table.jsx
  src/data/admin/Icons.js
Labels: Ready to Merge

#659 added margin bottom to make sign out higher
  src/components/Navigation.jsx
Labels: Navigation, Ready to Merge

#661 Sorting Tests
  cypress/e2e/admin/admin/Sort.cy.js
  cypress/e2e/admin/judges/Sort.cy.js
  cypress/e2e/admin/mentors/Sort.cy.js
  cypress/e2e/admin/participants/Sort.cy.js
  cypress/e2e/admin/teams/Sort.cy.js
  cypress/e2e/admin/volunteers/Sort.cy.js
  src/components/admin/Table.jsx
  src/components/admin/dashboards/SortIcon.jsx
Labels: Tests, Ready to Merge

#663 Added figma link to table
  cypress/fixtures/Teams.json
  src/data/admin/Icons.js
Labels: Teams, Ready to Merge

#662 textArea messenger, textArea mentor maxLength
  src/components/admin/services/Messenger.jsx
  src/components/admin/services/Textarea.jsx
  src/components/forms/Mentor.jsx
  src/components/forms/Textarea.jsx
Labels: Mentors, Messenger, Ready to Merge

#656 Admin Upload Component Tests
  cypress/component/admin/Upload.cy.jsx
  cypress/fixtures/files/extra.jpeg
  cypress/fixtures/files/extra.pdf
  cypress/fixtures/files/sample.jpg
  src/components/admin/services/Upload.jsx
Labels: Tests, Ready to Merge

#660 Lowercase File Names
  cypress/e2e/admin/admin/Actions.cy.js
  cypress/e2e/admin/admin/Filter.cy.js
  cypress/e2e/admin/admin/Search.cy.js
  cypress/e2e/admin/admin/Select.cy.js
  cypress/e2e/admin/admin/Sort.cy.js
  cypress/e2e/admin/judges/Actions.cy.js
  cypress/e2e/admin/judges/Filter.cy.js
  cypress/e2e/admin/judges/Search.cy.js
  cypress/e2e/admin/judges/Select.cy.js
  cypress/e2e/admin/judges/Sort.cy.js
  cypress/e2e/admin/mentors/Actions.cy.js
  cypress/e2e/admin/mentors/Filter.cy.js
  cypress/e2e/admin/mentors/Search.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/mentors/Sort.cy.js
  cypress/e2e/admin/participants/Actions.cy.js
  cypress/e2e/admin/participants/Filter.cy.js
  cypress/e2e/admin/participants/Search.cy.js
  cypress/e2e/admin/participants/Select.cy.js
  cypress/e2e/admin/participants/Sort.cy.js
  cypress/e2e/admin/teams/Actions.cy.js
  cypress/e2e/admin/teams/Filter.cy.js
  cypress/e2e/admin/teams/Search.cy.js
  cypress/e2e/admin/teams/Select.cy.js
  cypress/e2e/admin/teams/Sort.cy.js
  cypress/e2e/admin/volunteers/Actions.cy.js
  cypress/e2e/admin/volunteers/Filter.cy.js
  cypress/e2e/admin/volunteers/Search.cy.js
  cypress/e2e/admin/volunteers/Select.cy.js
  cypress/e2e/admin/volunteers/Sort.cy.js
  cypress/fixtures/TeamsCopy.json
  cypress/fixtures/admin.json
  cypress/fixtures/admins.json
  cypress/fixtures/checkin_user.json
  cypress/fixtures/events.json
  cypress/fixtures/judges.json
  cypress/fixtures/judges_list.json
  cypress/fixtures/mentors.json
  cypress/fixtures/participants.json
  cypress/fixtures/pie_charts.json
  cypress/fixtures/teams.json
  cypress/fixtures/user.json
  cypress/fixtures/volunteers.json
  src/components/admin/dashboards/Admins.jsx
  src/components/admin/dashboards/Judges.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/admin/dashboards/Teams.jsx
  src/components/admin/dashboards/Volunteers.jsx
  src/components/admin/services/Prizes.jsx
  src/components/admin/services/Statistics.jsx
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/admin/services/judging/Judging.jsx
  src/components/user/Dashboard.jsx
Labels: Tests, Judging, Ready to Merge

#667 Setup Conditional Releases
  cypress/e2e/admin/teams/Actions.cy.js
  cypress/e2e/admin/teams/Filter.cy.js
  cypress/e2e/admin/teams/Search.cy.js
  cypress/e2e/admin/teams/Select.cy.js
  cypress/e2e/admin/teams/Sort.cy.js
  cypress/fixtures/Teams.json
  cypress/fixtures/teams.json
  src/app/page.js
  src/components/Release.jsx
  src/components/admin/dashboards/Teams.jsx
  src/data/Release.js
Labels: Ready to Merge

#674 Check In Backend
  cypress/fixtures/checkin_user.json
  cypress/fixtures/events.json
  src/app/api/checkin/route.js
  src/components/admin/services/DropDown.jsx
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/forms/Admin.jsx
  src/components/forms/Feedback.jsx
  src/components/forms/Judge.jsx
  src/components/forms/Mentor.jsx
  src/components/forms/Register.jsx
  src/components/forms/Volunteer.jsx
Labels: Ready to Merge

#675 dropdown comp test
  cypress/component/admin/Dropdown.cy.jsx
  src/components/admin/services/DropDown.jsx
Labels: Tests, Ready to Merge

#666 Add Feedback Form to User Navigation
  cypress/e2e/admin/Navigation.cy.js
  src/app/admin/feedback/page.js
  src/components/forms/Feedback.jsx
  src/data/Navigation.js
Labels: Navigation, Bug Fix, Ready to Merge, Forms

#676 Jonathan/added members
  cypress/fixtures/teams.json
Labels: Ready to Merge

#680 Prizes Backend
  cypress/fixtures/prizes.json
  cypress/fixtures/teams.json
  src/app/api/prizes/route.js
  src/components/admin/services/Prizes.jsx
  src/components/admin/services/Toolbar.jsx
  src/components/admin/services/checkin/CheckIn.jsx
Labels: Ready to Merge

#684 Menthy/dropdown
  src/components/admin/services/DropDown.jsx
  src/components/admin/services/Toolbar.jsx
Labels: Ready for Review

#678 Menthy/mentortests
  cypress/e2e/admin/mentors/Actions.cy.js
  cypress/e2e/admin/mentors/Filter.cy.js
  cypress/e2e/admin/mentors/Search.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/mentors/Sort.cy.js
  cypress/fixtures/mentors.json
  src/components/admin/Table.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/SortIcon.jsx
Labels: Ready for Review

#687 participants backend
  src/app/api/participants/route.js
  src/components/ProtectedPage.jsx
  src/components/admin/Table.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/forms/Mentor.jsx
  src/components/forms/Register.jsx
  src/components/forms/Volunteer.jsx
Labels: Participants, Ready for Review, Backend

#695 Hackathon Config
  src/app/page.js
  src/components/Navigation.jsx
  src/components/admin/services/Messenger.jsx
  src/data/Config.js
  src/data/Release.js
  src/data/forms/Admins.js
  src/data/forms/Committees.js
  src/data/forms/Feedback.js
  src/data/forms/Judge.js
  src/data/forms/Mentors.js
  src/data/forms/Register.js
  src/data/forms/Volunteers.js
Labels: Ready to Merge

#698 Participant Backend Testing
  cypress/e2e/admin/participants/Actions.cy.js
  cypress/e2e/admin/participants/Filter.cy.js
  cypress/e2e/admin/participants/Search.cy.js
  cypress/e2e/admin/participants/Select.cy.js
  cypress/e2e/admin/participants/Sort.cy.js
Labels: Participants, Tests, Backend
