Repository acm-ucr/aurora, pull requests merged in 2023-12, with the labels that each got.

#928 Sponsors Form
  cypress/e2e/admin/Navigation.cy.js
  cypress/e2e/admin/sponsors/Actions.cy.js
  cypress/e2e/admin/sponsors/Filter.cy.js
  cypress/e2e/admin/sponsors/Search.cy.js
  cypress/e2e/admin/sponsors/Select.cy.js
  cypress/e2e/admin/sponsors/Sort.cy.js
  cypress/fixtures/sponsors.json
  src/app/admin/sponsors/page.js
  src/app/api/messenger/route.js
  src/app/api/sponsors/route.js
  src/app/api/statistics/route.js
  src/app/form/sponsor/page.js
  src/app/sitemap.js
  src/components/dynamic/admin/dashboards/Sponsors.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/data/Releases.js
  src/data/dynamic/Navigation.js
  src/data/dynamic/Tags.js
  src/data/dynamic/admin/Sponsors.js
  src/data/dynamic/form/Sponsors.js
Labels: Ready for Review, Forms, Sponsors

#925 Add Compression
  cypress/component/admin/Upload.cy.jsx
  package-lock.json
  package.json
  src/components/dynamic/admin/services/Messenger.jsx
  src/components/dynamic/admin/services/Upload.jsx
  src/components/dynamic/form/Upload.jsx
  src/utils/convert.js
Labels: Ready to Merge

#931 remove instances of team names
  package-lock.json
  package.json
  src/app/api/team/route.js
  src/app/api/teams/route.js
  src/components/dynamic/user/Team.jsx
Labels: Ready for Review

#934 moved firebase into /utils and updated imports
  src/app/api/admins/route.js
  src/app/api/checkin/route.js
  src/app/api/committees/route.js
  src/app/api/feedback/route.js
  src/app/api/interests/route.js
  src/app/api/judges/route.js
  src/app/api/judging/route.js
  src/app/api/members/route.js
  src/app/api/mentors/route.js
  src/app/api/messenger/route.js
  src/app/api/participant/route.js
  src/app/api/participants/route.js
  src/app/api/prizes/route.js
  src/app/api/sponsors/route.js
  src/app/api/statistics/route.js
  src/app/api/team/route.js
  src/app/api/teams/route.js
  src/app/api/volunteers/route.js
  src/utils/firebase.js
Labels: Ready for Review, Register

#930 sponsorship packet on form
  src/components/dynamic/form/Questions.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/data/Config.js
Labels: Ready for Review, Forms

#933 Seanquiambao/mentorstatus
  src/app/api/mentors/route.js
  src/data/dynamic/admin/Mentors.js
Labels: Ready for Review

#940 Change Ordering
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Volunteers.js
  src/data/dynamic/form/Information.js
Labels: Ready for Review

#937 Extend Custom Error
  src/app/error.js
  src/components/dynamic/Error.jsx
  src/utils/error.js
Labels: Repository, Ready to Merge

#924 Prevent API Call
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready to Merge, Dashboards

#941 add dashboard toolbar shortcuts
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready to Merge

#942 added prizes input validation
  src/components/dynamic/admin/services/Toolbar.jsx
Labels: Ready for Review, Bug Fix, Prizes

#943 cron job fix
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#964 acm custom workflows for linting, build, formatting
  .github/workflows/pull-request.yaml
Labels: Ready for Review, Repository

#967 Fuyuki/RemoveUpcomingPrelive
  src/app/page.js
  src/components/static/prelive/Prelive.jsx
  src/components/static/upcoming/Upcoming.jsx
  src/data/Releases.js
Labels: Ready for Review

#968 Fuyuki/MoveSessionProvider
  src/app/layout.js
  src/components/dynamic/Session.jsx
Labels: Ready for Review

#966 Sign Out Button Form
  src/components/dynamic/ProtectedPage.jsx
  src/components/dynamic/form/Form.jsx
Labels: Ready for Review, Forms

#965 simplified Checkbox
  cypress/e2e/admin/admins/Select.cy.js
  cypress/e2e/admin/committees/Select.cy.js
  cypress/e2e/admin/judges/Select.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/participants/Select.cy.js
  cypress/e2e/admin/sponsors/Select.cy.js
  cypress/e2e/admin/teams/Select.cy.js
  cypress/e2e/admin/volunteers/Select.cy.js
  package-lock.json
  src/components/dynamic/Checkbox.jsx
  src/components/dynamic/admin/dashboards/Toolbar.jsx
Labels: Ready for Review, Dashboards

#945 fixed dashboard view issue
  src/components/dynamic/user/Dashboard.jsx
Labels: Ready for Review

#970 consolidated forms routes
  src/app/form/[type]/page.js
  src/app/form/admin/page.js
  src/app/form/committee/page.js
  src/app/form/feedback/page.js
  src/app/form/interest/page.js
  src/app/form/judge/page.js
  src/app/form/mentor/page.js
  src/app/form/participant/page.js
  src/app/form/sponsor/page.js
  src/app/form/volunteer/page.js
  src/components/dynamic/form/Judge.jsx
Labels: Ready for Review, Forms

#969 changed team api to save discord instead of email
  src/app/api/team/route.js
  src/app/api/teams/route.js
  src/data/dynamic/admin/Teams.js
Labels: Teams, Ready for Review, Backend

#975 change link color to green
  src/components/dynamic/form/Questions.jsx
Labels: Ready for Review

#976 Judging Rennovations
  src/components/dynamic/admin/services/judging/Judging.jsx
  src/components/dynamic/admin/services/judging/Table.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready for Review

#916 Menthy/api
  cypress/component/admin/dashboards/Toolbar.cy.jsx
  cypress/downloads/admins.gz
  cypress/support/commands.js
  src/app/api/admins/route.js
  src/app/api/committees/route.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/dashboard/feedback/route.js
  src/app/api/dashboard/teams/route.js
  src/app/api/interests/route.js
  src/app/api/judges/route.js
  src/app/api/mentors/route.js
  src/app/api/participants/route.js
  src/app/api/sponsors/route.js
  src/app/api/teams/route.js
  src/app/api/volunteers/route.js
  src/components/dynamic/admin/Table.jsx
  src/components/dynamic/admin/dashboards/Toolbar.jsx
  src/components/dynamic/form/Admin.jsx
  src/components/dynamic/form/Committee.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Interest.jsx
  src/components/dynamic/form/Judge.jsx
  src/components/dynamic/form/Mentor.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/components/dynamic/form/Volunteer.jsx
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Dashboard.js
  src/data/dynamic/admin/Feedback.js
  src/data/dynamic/admin/Interest.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Sponsors.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready for Review, Backend

#977 Change Email Service
  cypress/component/admin/dashboards/Toolbar.cy.jsx
  package-lock.json
  package.json
  src/app/api/dashboard/[type]/route.js
  src/app/api/messenger/route.js
  src/components/dynamic/form/Volunteer.jsx
  src/utils/email.js
  src/utils/sendgrid.js
Labels: Ready for Review

#980 changed cronjob to run every two days
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#938 Setup New API and Remove Axios
  src/app/user/join/[teamID]/page.js
  src/components/dynamic/admin/dashboards/Toolbar.jsx
  src/components/dynamic/admin/services/Toolbar.jsx
  src/components/dynamic/admin/services/calendar/Events.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
  src/components/dynamic/admin/services/statistics/Statistics.jsx
  src/components/dynamic/form/Admin.jsx
  src/components/dynamic/form/Committee.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Interest.jsx
  src/components/dynamic/form/Judge.jsx
  src/components/dynamic/form/Mentor.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/components/dynamic/form/Volunteer.jsx
  src/components/dynamic/user/Team.jsx
  src/components/dynamic/user/User.jsx
  src/utils/api.js
Labels: Ready for Review

#981 consolidated admin
  src/app/admin/[type]/page.js
  src/app/admin/admins/page.js
  src/app/admin/calendar/page.js
  src/app/admin/checkin/page.js
  src/app/admin/committees/page.js
  src/app/admin/feedback/page.js
  src/app/admin/interests/page.js
  src/app/admin/judges/page.js
  src/app/admin/judging/page.js
  src/app/admin/mentors/page.js
  src/app/admin/messenger/page.js
  src/app/admin/participants/page.js
  src/app/admin/prizes/page.js
  src/app/admin/sponsors/page.js
  src/app/admin/statistics/page.js
  src/app/admin/teams/page.js
  src/app/admin/volunteers/page.js
  src/app/api/judging/route.js
Labels: Ready for Review, Admin

#932 Remove Team Name
  cypress/e2e/admin/teams/Sort.cy.js
  cypress/fixtures/teams.json
  src/data/dynamic/admin/Teams.js
Labels: Teams, Ready to Merge

#983 made links apear conditionally
  src/components/dynamic/admin/services/judging/Table.jsx
Labels: Ready for Review, Judging

#985 fix spelling
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Sponsors.js
Labels: Ready for Review
