Repository acm-ucr/aurora, pull requests merged in 2024-01, with the labels that each got.

#987 simplify loading
  src/app/loading.js
Labels: Ready for Review

#1003 team tag and placeholder on toolbar
  src/components/dynamic/admin/services/Toolbar.jsx
Labels: Ready for Review, Prizes

#1004 Fix Undefined State Error
  src/components/dynamic/form/Volunteer.jsx
Labels: Ready for Review

#1005 Refactor Messenger to Contacts
  src/app/admin/[type]/page.js
  src/app/api/contacts/route.js
  src/app/api/messenger/route.js
  src/components/dynamic/Select.jsx
  src/components/dynamic/admin/services/Messenger.jsx
  src/components/dynamic/admin/services/contacts/Contact.jsx
  src/components/dynamic/admin/services/contacts/Contacts.jsx
  src/data/dynamic/Navigation.js
Labels: Ready for Review

#1008 Add Confetti Animation
  package-lock.json
  package.json
  src/components/dynamic/form/Confirmation.jsx
Labels: Ready for Review

#1010 Convert to Lowercase in Tags when Printing Text
  cypress/component/admin/Tag.cy.jsx
  src/components/dynamic/admin/Tag.jsx
Labels: Ready for Review

#1017 fix template sync for yaml files
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#1016 Seanquiambao/calendarfetch
  package-lock.json
  package.json
  src/app/user/join/[teamID]/page.js
  src/components/dynamic/admin/services/calendar/Events.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/user/Team.jsx
Labels: Do Not Merge

#1009 Fuyuki/RadioTesting
  cypress/component/Radio.cy.jsx
  src/components/dynamic/Radio.jsx
Labels: Ready for Review

#1020 fixed file paths
  src/components/dynamic/form/Admin.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Judge.jsx
  src/components/dynamic/form/Mentor.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Volunteer.jsx
Labels: Ready for Review

#1021 fixed spelling
  src/components/dynamic/admin/dashboards/Committees.jsx
  src/components/dynamic/form/Status.jsx
Labels: Ready for Review

#1018 Make stats page use statistics document instead of querying users
  src/app/api/dashboard/[type]/route.js
  src/app/api/statistics/route.js
  src/components/dynamic/admin/services/statistics/Statistics.jsx
Labels: Statistics, Ready for Review

#1032 Fix Table Styling
  cypress/support/commands.js
  src/components/dynamic/ProtectedPage.jsx
  src/components/dynamic/admin/dashboards/dashboard/Dashboard.jsx
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review

#1013 parallel read/write user and admin
  src/app/api/dashboard/[type]/route.js
Labels: Ready for Review, User Portal, Backend

#1035 add error page for auth error
  src/app/api/auth/[...nextauth]/route.js
  src/app/auth/error/page.js
Labels: Ready to Merge

#1036 Virtualize List
  cypress/component/Select.cy.jsx
  cypress/component/form/Textarea.cy.jsx
  cypress/component/form/Upload.cy.jsx
  package-lock.json
  package.json
  src/components/dynamic/Input.jsx
  src/components/dynamic/Radio.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/admin/services/contacts/Contact.jsx
  src/components/dynamic/form/Admin.jsx
  src/components/dynamic/form/Committee.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Interest.jsx
  src/components/dynamic/form/Judge.jsx
  src/components/dynamic/form/Mentor.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/components/dynamic/form/Volunteer.jsx
  src/components/dynamic/form/form/Confirmation.jsx
  src/components/dynamic/form/form/Form.jsx
  src/components/dynamic/form/form/Questions.jsx
  src/components/dynamic/form/form/Status.jsx
  src/components/dynamic/form/form/Textarea.jsx
  src/components/dynamic/form/form/Upload.jsx
  src/data/dynamic/form/Information.js
  src/data/dynamic/form/Schools.js
Labels: Ready for Review

#1068 Change Default Asterisk Color
  src/components/dynamic/form/form/Questions.jsx
Labels: Ready for Review, Forms

#1067 integrated signout into button
  src/components/dynamic/form/form/Form.jsx
Labels: Ready for Review, Forms

#1070 fix title casing
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready for Review, Admin, Dashboards

#1071 fixed checkbox spacing
  src/components/dynamic/Checkbox.jsx
  src/components/dynamic/form/form/Questions.jsx
Labels: Ready for Review, Forms

#1069 added default diet restriction
  src/data/dynamic/admin/Participants.js
Labels: Participants, Ready for Review

#1079 fix cron job
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#1085 centered arrows
  src/components/dynamic/admin/dashboards/dashboard/Body.jsx
Labels: Ready for Review

#1066 Fix stats page implementation to work with other hackathon websites
  src/app/admin/[type]/page.js
  src/app/api/settings/route.js
  src/components/dynamic/admin/services/settings/Settings.jsx
Labels: Ready for Review

#1089 disabled view loading
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready for Review

#1086 made icons transparent
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
Labels: Ready for Review

#1087 changed nav header
  src/components/dynamic/Navigation.jsx
  src/data/Config.js
Labels: Ready for Review

#1088 added metadata to forms
  src/data/Config.js
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Feedback.js
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready for Review

#1063 Parallel Read/Write - Forms
  src/app/api/judging/route.js
Labels: Forms, Backend, Performance

#1090 Memoize Components
  src/components/dynamic/admin/dashboards/dashboard/Filter.jsx
Labels: Repository

#1065 added SelectAll component
  src/components/dynamic/form/form/Questions.jsx
  src/components/dynamic/form/form/Terms.jsx
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready for Review, Forms
