Repository acm-ucr/aurora, pull requests merged in 2024-04, with the labels that each got.

#1254 combined exports
  src/app/manifest.js
  src/app/sitemap.js
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/form/form/Questions.jsx
  src/data/Config.js
  src/data/dynamic/Navigation.js
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Feedback.js
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Leads.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Panelists.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready for Review

#1262 Fix Calendar
  src/components/dynamic/admin/services/calendar/CalendarWrapper.jsx
  src/components/dynamic/admin/services/calendar/Events.jsx
  src/components/dynamic/admin/services/calendar/Toolbar.jsx
  src/data/dynamic/admin/Calendar.js
Labels: Ready for Review, Calendar

#1260 logout button
  src/components/dynamic/user/Header.jsx
Labels: Ready for Review

#1261 added hackathon nav item & header
  package-lock.json
  src/app/engineering/hackathons/page.js
  src/components/engineering/hackathons/Hackathons.jsx
  src/components/engineering/hackathons/Header.jsx
  src/data/engineering/Navigation.js
Labels: Ready for Review

#1263 Resend Email Automation
  .github/workflows/pull-request.yaml
  package-lock.json
  package.json
  src/app/api/dashboard/[type]/route.js
  src/components/email/Acceptance.jsx
  src/components/email/Confirmation.jsx
  src/components/email/Email.jsx
  src/components/email/Rejection.jsx
  src/components/email/Template.jsx
  src/data/Config.js
  src/utils/email.js
Labels: Ready for Review

#1268 Enabled Loading In Table Page Switching
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review

#1271 judging, rule, hackpack
  src/components/user/BulletPoints.jsx
  src/components/user/Collapse.jsx
  src/components/user/Dashboard.jsx
  src/components/user/Hackpack.jsx
  src/components/user/Hackpacks.jsx
  src/components/user/Judging.jsx
  src/components/user/Rules.jsx
  src/data/user/Hackpacks.js
  src/data/user/Judging.jsx
  src/data/user/Rules.js
Labels: Ready for Review

#1280 Changed all instances of normal functions to arrow functions
  src/app/api/checkin/route.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/dashboard/feedback/route.js
  src/app/api/dashboard/teams/route.js
  src/app/api/judging/route.js
  src/app/api/members/route.js
  src/app/api/participant/route.js
  src/app/api/statistics/route.js
  src/app/api/team/route.js
  src/app/error.js
  src/app/user/join/[teamID]/page.js
  src/components/engineering/Blog.jsx
Labels: Repository

#1274 Fixed overflow issue with navbar tabs
  src/components/Navigation.jsx
Labels: Navigation

#1269 Re-did count down component
  src/components/user/Countdown.jsx
  src/data/Config.js
Labels: User Portal

#1267 cursor animation
  src/components/engineering/Blog.jsx
Labels: Ready for Review

#1294 Engineering Blog - React Table
  src/engineering/react-table.mdx
Labels: Ready for Review, Engineering

#1298 removed all instances of importing React
  src/components/admin/services/Upload.jsx
  src/components/user/Countdown.jsx
  src/components/user/Tile.jsx
Labels: Repository

#1295 countdown is now larger
  src/components/user/Countdown.jsx
Labels: Ready for Review

#1296 changed parking link
  src/components/user/Dashboard.jsx
Labels: Ready for Review

#1297 moved rules, and set initial state to rules
  src/components/user/Dashboard.jsx
Labels: Ready for Review

#1307 fixed articles mobile responsiveness
  src/components/engineering/Blog.jsx
Labels: Ready for Review

#1306 mobile responsiveness on the RIGHT repo this time
  src/components/engineering/Landing.jsx
  src/components/engineering/What.jsx
Labels: Ready for Review

#1310 responsiveness for hackathons page
  src/components/engineering/hackathons/Hackathons.jsx
Labels: Ready for Review

#1313 Added Resources
  src/components/form/form/Questions.jsx
Labels: Ready for Review

#1312 Added Terms and Conditions
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Interest.js
  src/data/form/Judge.js
  src/data/form/Leads.js
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Participant.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Ready for Review

#1311 Logout Hover Animation
  src/components/user/Header.jsx
Labels: Ready for Review
