Repository acm-ucr/aurora, pull requests merged in 2024-12, with the labels that each got.

#1895 ShadCN Sidebar Migration
  package-lock.json
  package.json
  src/components/navigation.tsx
  src/components/protected.jsx
  src/components/providers.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-mobile.tsx
  tailwind.config.js
Labels: Do Not Merge, Admin, Dashboards, Shadcn

#1897 miscellaneous
  src/components/checkbox.tsx
  src/components/form/form/terms.tsx
Labels: Bug Fix

#1901 added hover to radio components
  src/components/ui/label.tsx
Labels: Bug Fix

#1904 sticky and x gets text removed
  src/components/user/resources/resources.tsx
  src/components/user/toolbar.tsx
Labels: Ready for Review, Hackpack
