Repository acm-ucr/aurora, pull requests merged in 2024-09, with the labels that each got.

#1789 user checkin page.js to ts
  src/app/user/checkin/page.tsx
Labels: Typescript

#1790 pre-commit to pre-push
  .husky/pre-push
Labels: Ready for Review

#1779 changed dashboard/lead to ts
  src/data/admin/Leads.tsx
Labels: Ready for Review, Typescript

#1780 Changed feedback to ts
  src/data/admin/Feedback.tsx
Labels: Ready for Review, Typescript

#1792 Included all usertypes
  src/app/api/settings/route.js
Labels: Ready for Review

#1760 Converted email.js to ts
  package-lock.json
  package.json
  src/utils/email.js
  src/utils/email.ts
Labels: Ready for Review, Typescript

#1703 zod
  src/components/form/Admin.jsx
  src/components/form/Committee.jsx
  src/components/form/Feedback.jsx
  src/components/form/Ideas.jsx
  src/components/form/Interest.jsx
  src/components/form/Judge.jsx
  src/components/form/Lead.jsx
  src/components/form/Mentor.jsx
  src/components/form/Panelist.jsx
  src/components/form/Participant.jsx
  src/components/form/Sponsor.jsx
  src/components/form/Volunteer.jsx
  src/schemas/admin.ts
  src/schemas/committee.ts
  src/schemas/feedback.ts
  src/schemas/idea.ts
  src/schemas/interest.ts
  src/schemas/judge.ts
  src/schemas/lead.ts
  src/schemas/mentor.ts
  src/schemas/panel.ts
  src/schemas/participant.ts
  src/schemas/sponsor.ts
  src/schemas/volunteer.ts
  src/utils/form.ts
Labels: Ready for Review

#1799 change User Resources page to ts
  src/app/user/resources/page.tsx
Labels: Ready for Review, Typescript

#1800 remove year, calculate year based on date
  src/data/Config.ts
  src/data/admin/Judges.tsx
Labels: Ready for Review, Repository

#1803 Fix Engineering Blog
  package-lock.json
  package.json
  src/app/engineering/blog/[type]/page.js
  src/engineering/judging.mdx
  tailwind.config.js
Labels: Bug Fix, Engineering

#1802 Reduce Padding
  src/components/admin/dashboards/dashboard/Body.jsx
Labels: Dashboards

#1801 fixes shirt sizes being saved as role status
  src/app/api/dashboard/[type]/route.js
Labels: Ready for Review, Bug Fix

#1776 Convert engineering nav data to Typescript
  src/data/engineering/Navigation.tsx
Labels: Ready for Review, Typescript

#1718 converted committees to typescript
  src/data/admin/Committees.tsx
Labels: Ready for Review, Committee

#1806 Bigger icons
  src/components/admin/Input.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review, Dashboards

#1805 User Teams
  src/app/user/join/[teamID]/page.tsx
Labels: Ready for Review, Typescript

#1809 Changed file to error.tsx
  src/app/error.js
  src/app/error.tsx
Labels: Ready for Review, Typescript

#1804 Add Subheadings
  src/components/admin/Subtitle.tsx
  src/components/admin/services/statistics/Statistics.jsx
  src/components/admin/services/statistics/Tabs.jsx
Labels: Statistics, Ready to Merge

#1797 attempt to format contacts, make vertical cards
  src/components/admin/services/contacts/Contact.jsx
  src/components/admin/services/contacts/Contacts.tsx
  src/data/Navigation.tsx
Labels: Ready for Review

#1656 React Query Migration
  .eslintrc.json
  package-lock.json
  package.json
  src/app/admin/[type]/page.js
  src/app/api/statistics/route.js
  src/app/layout.tsx
  src/components/Providers.tsx
  src/components/Session.tsx
  src/components/admin/services/calendar/Calendar.jsx
  src/components/admin/services/calendar/Event.tsx
  src/components/admin/services/calendar/Events.jsx
  src/components/admin/services/calendar/Modal.jsx
  src/components/admin/services/calendar/actions.ts
  src/components/admin/services/calendar/index.tsx
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/admin/services/checkin/actions.ts
  src/components/admin/services/checkin/index.tsx
  src/components/admin/services/statistics/Charts.jsx
  src/components/admin/services/statistics/Statistics.jsx
  src/components/admin/services/statistics/actions.ts
  src/components/admin/services/statistics/index.tsx
  src/data/admin/Calendar.ts
  src/types/calendar.ts
  src/utils/react-query.tsx
Labels: Ready for Review, Good First Issue

#1808 toolbar filtering by description tags
  src/components/user/schedule/Schedule.jsx
Labels: Ready for Review, User Portal, Calendar

#1812 Fix Dropdown
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Bug Fix, Dashboards

#1811 changed length datatype to number
  src/data/Config.ts
  src/data/form/Admins.ts
  src/data/form/Committees.ts
  src/data/form/Ideas.js
  src/data/form/Interest.ts
  src/data/form/Judge.ts
  src/data/form/Mentors.ts
  src/data/form/Panelists.ts
  src/data/form/Participant.ts
  src/data/form/Sponsors.ts
  src/data/form/Volunteers.ts
Labels: Repository

#1810 added input otp for number of rotations
  package-lock.json
  src/components/admin/services/judging/Toolbar.jsx
Labels: Ready for Review, Judging, Shadcn

#1709 Add distribution labels
  src/components/admin/services/statistics/Chart.jsx
  src/components/admin/services/statistics/ChartLegend.jsx
  src/components/admin/services/statistics/Charts.jsx
  src/components/admin/services/statistics/Statistics.jsx
  src/components/admin/services/statistics/Tabs.jsx
Labels: Statistics, Do Not Merge, Dashboards

#1819 add next-route-visualizer
  package-lock.json
  package.json
  src/app/visualize/page.tsx
Labels: Ready for Review

#1813 Derrick mao/shadcn badge
  package-lock.json
  package.json
  src/components/admin/Tag.jsx
  src/components/ui/badge.tsx
Labels: Ready for Review

#1848 added default message
  src/components/user/find/Find.jsx
Labels: Bug Fix, User Portal

#1851 migrate contacts from js to ts
  src/app/api/contacts/route.ts
  src/types/contacts.ts
Labels: Ready for Review

#1849 clickable text options
  src/components/form/form/Questions.jsx
Labels: Bug Fix, Forms

#1845 Shadow/cardlink
  cypress/component/user/Hackpack.cy.jsx
  src/components/user/resources/Hackpack.tsx
Labels: Ready for Review, User Portal

#1807 Change Columns and Tag to tsx
  src/components/Checkbox.tsx
  src/components/admin/Tag.jsx
  src/components/admin/Tag.tsx
  src/data/Statuses.ts
  src/data/admin/Columns.js
  src/data/admin/Columns.tsx
Labels: Ready for Review, Typescript

#1858 enabled search for hackpacks
  src/components/user/find/Toolbar.jsx
  src/components/user/resources/Resources.tsx
Labels: Ready for Review

#1865 dropdown search visibility
  src/components/Select.jsx
Labels: Bug Fix, Forms

#1861 fix contacts responsiveness
  src/components/admin/services/contacts/Contact.jsx
  src/components/admin/services/contacts/Contacts.tsx
Labels: Bug Fix, Contacts
