Repository acm-ucr/aurora, pull requests merged in 2024-07, with the labels that each got.

#1506 made two columns for checkboxes
  src/components/form/form/Questions.jsx
Labels: Forms

#1503 created event component test (again)
  cypress/component/admin/Event.cy.jsx
  package-lock.json
  src/components/admin/services/calendar/Event.jsx
Labels: Ready for Review

#1507 Checkin Engineering Blog
  src/components/admin/services/checkin/CheckIn.jsx
  src/engineering/checkin.mdx
Labels: Engineering

#1512 Added Back to Home button for forms
  src/components/form/form/Form.jsx
Labels: Ready for Review, Forms

#1423 added live sections, temp faq and schedule set up
  cypress/component/form/Confirmation.cy.jsx
  src/app/page.js
  src/components/live/About.jsx
  src/components/live/Committees.jsx
  src/components/live/Footer.jsx
  src/components/live/Judges.jsx
  src/components/live/Landing.jsx
  src/components/live/Live.jsx
  src/components/live/Sponsors.jsx
  src/components/live/Team.jsx
  src/components/live/Tracks.jsx
  src/components/live/faq/FAQ.jsx
  src/components/live/faq/Item.jsx
  src/components/live/schedule/Events.jsx
  src/components/live/schedule/Schedule.jsx
  src/components/user/schedule/Events.jsx
  src/data/FAQ.js
Labels: Ready for Review, Live

#1516 teams appears now along with team id
  package-lock.json
  package.json
  src/app/api/dashboard/teams/route.js
  src/data/admin/Dashboard.js
  src/data/admin/Teams.js
Labels: Ready for Review

#1515 engineering blogs sorted
  src/components/engineering/Blog.jsx
Labels: Ready for Review, Engineering

#1513 Made placeholders more consistent
  src/components/admin/services/contacts/Contact.jsx
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Feedback.js
  src/data/form/Interest.js
  src/data/form/Judge.js
  src/data/form/Leads.js
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Participant.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Forms

#1509 Change view button text
  src/components/admin/services/judging/Toolbar.jsx
Labels: Do Not Merge, Judging

#1508 Changed all instances of toast to toaster
  src/components/form/Lead.jsx
  src/components/form/Panelist.jsx
Labels: Do Not Merge

#1505 add Teams/Judges title
  src/components/admin/services/judging/Judging.jsx
Labels: Ready for Review, Do Not Merge, Judging

#1439 add component test for Status.jsx
  cypress/component/form/Status.cy.jsx
  src/components/form/form/Status.jsx
Labels: Ready for Review, Do Not Merge

#1510 Add opacity change
  src/components/form/form/Questions.jsx
Labels: Do Not Merge, Forms

#1501 1478 iconize nav
  .gitignore
  src/components/Navigation.jsx
  src/data/Navigation.js
Labels: Navigation, Ready for Review

#1519 schedule blog
  src/engineering/Schedule.mdx
Labels: Ready for Review, Engineering

#1511 made parallel call for checkin route
  src/app/api/checkin/route.js
Labels: Do Not Merge, Check In, Tests, Backend, Performance

#1518 User Portal Schedule
  package-lock.json
  src/app/user/schedule/page.js
  src/components/user/schedule/Events.jsx
  src/components/user/schedule/Schedule.jsx
  src/components/user/schedule/Wrapper.jsx
Labels: Ready for Review

#1517 Run Firestore and Resend Email Calls in Parallel
  src/app/api/dashboard/[type]/route.js
Labels: Ready for Review, Dashboards, Performance

#1520 Fix Participant Bug
  src/data/form/Participant.js
Labels: Participants, Bug Fix, Ready to Merge, Forms

#1504 Mighty mango1/update packing list
  src/components/user/Packing.jsx
Labels: Ready for Review, User Portal

#1524 Statistics Blog
  src/engineering/statistics.mdx
Labels: Ready for Review, Engineering

#1526 create loading component test
  src/components/Loading.cy.jsx
Labels: Tests, Good First Issue

#1527 Created E2E tests for Leads
  cypress/e2e/admin/leads/Actions.cy.js
  cypress/e2e/admin/leads/Filter.cy.js
  cypress/e2e/admin/leads/Search.cy.js
  cypress/e2e/admin/leads/Select.cy.js
  cypress/fixtures/leads.json
Labels: Ready for Review, Tests

#1523 add component test for BulletPoints.jsx
  cypress/component/user/BulletPoints.cy.jsx
  src/components/user/BulletPoints.jsx
Labels: Ready for Review, Tests

#1488 Abstracted Join to Custom Component
  src/actions/join.js
  src/app/user/join/[teamID]/page.js
  src/components/user/join/Join.jsx
  src/components/user/join/JoinClient.jsx
Labels: Ready for Review, User Portal

#1530 Finish E2E for Interests
  cypress/e2e/admin/interests/Actions.cy.js
  cypress/e2e/admin/interests/Filter.cy.js
  cypress/e2e/admin/interests/Search.cy.js
  cypress/e2e/admin/interests/Select.cy.js
  cypress/fixtures/interests.json
Labels: Ready for Review, Tests

#1529 tile parking & check in component test
  cypress/component/user/Tile.cy.jsx
  package-lock.json
  package.json
  src/components/user/Tile.jsx
Labels: Ready for Review

#1522 Fixed Change Settings Logging #1150 and Completed Reduce Spacing #1183
  src/components/admin/services/settings/Settings.jsx
  src/components/form/form/Questions.jsx
Labels: Settings

#1531 Bug Fixes
  src/components/admin/services/settings/Settings.jsx
  src/data/admin/Columns.js
Labels: Bug Fix

#1451 github action blog added
  src/engineering/github-actions.mdx
Labels: Do Not Merge, Engineering

#1548 implemented shadcn checkbox + install
  components.json
  cypress/component/Checkbox.cy.jsx
  package-lock.json
  package.json
  src/app/globals.css
  src/components/Checkbox.jsx
  src/components/ui/checkbox.jsx
  src/utils/utils.js
  tailwind.config.js
Labels: Ready for Review

#1550 Fixed Empty Message
  src/components/admin/services/judging/Judging.jsx
Labels: Judging

#1551 Team Creation + Join
  src/engineering/team.mdx
Labels: Ready for Review, Engineering

#1554 added teams
  src/data/Navigation.js
Labels: Ready for Review

#1552 Added Spacing
  package-lock.json
  src/components/admin/dashboards/dashboard/Toolbar.jsx
  src/components/ui/checkbox.jsx
Labels: Ready for Review, Admin, Dashboards

#1557 Navigation Responsiveness
  src/components/engineering/Navigation.jsx
  src/data/engineering/Navigation.js
Labels: Ready for Review, Engineering

#1560 Add responsiveness to scanner
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/admin/services/checkin/Scanner.jsx
Labels: Ready for Review, Check In

#1559 Shadcn Statistics
  package-lock.json
  package.json
  src/app/api/statistics/route.js
  src/components/admin/services/statistics/Chart.jsx
  src/components/admin/services/statistics/Charts.jsx
  src/components/admin/services/statistics/Statistics.jsx
  src/components/admin/services/statistics/Tabs.jsx
  src/components/ui/card.jsx
  src/components/ui/chart.jsx
  src/data/admin/Statistics.js
Labels: Statistics, Ready for Review

#1565 Made # of rotations box smaller
  package-lock.json
  src/components/admin/services/judging/Toolbar.jsx
Labels: Judging

#1571 Column Spacing
  src/data/admin/Teams.js
Labels: Teams, Ready for Review, Dashboards

#1569 made day of week sticky
  src/components/user/schedule/Schedule.jsx
Labels: Ready for Review, User Portal

#1561 added hackathon logo to hackathon engineering site + fixed text opaci…
  src/components/engineering/Navigation.jsx
  src/components/form/form/Questions.jsx
Labels: Engineering, Good First Issue

#1564 Centered Text
  src/components/engineering/Blog.jsx
Labels: Engineering, Good First Issue

#1566 Updated Rules
  src/data/user/Rules.js
Labels: Ready for Review, User Portal

#1556 add component test for Hackpack.jsx
  cypress/component/user/Hackpack.cy.jsx
  src/components/user/Hackpack.jsx
Labels: Ready for Review, Tests

#1647 Redesign Team Pages
  package-lock.json
  package.json
  src/actions/join.js
  src/app/api/members/route.js
  src/app/api/team/route.js
  src/components/ui/alert-dialog.jsx
  src/components/ui/button.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/tabs.jsx
  src/components/user/join/Invite.jsx
  src/components/user/join/Join.jsx
  src/components/user/join/JoinClient.jsx
  src/components/user/team/Details.jsx
  src/components/user/team/NewTeam.jsx
  src/components/user/team/Team.jsx
  src/utils/auth.ts
Labels: Shadcn

#1653 Made Tab component test
  cypress/component/admin/Tab.cy.jsx
Labels: Tests, Good First Issue

#1655 removed cursor animation on hover
  src/components/user/BulletList.jsx
Labels: Ready for Review, User Portal

#1661 schools to typescript
  src/data/form/Schools.ts
Labels: Typescript

#1659 Convert rooms to Typescript
  src/components/user/Rooms.tsx
Labels: Ready for Review, Typescript

#1658 Convert release to Typescript
  src/components/Release.jsx
  src/components/Release.tsx
Labels: Ready for Review, Typescript

#1657 Convert Tailwind Util to Typescript
  components.json
  src/components/ui/alert-dialog.jsx
  src/components/ui/button.jsx
  src/components/ui/card.jsx
  src/components/ui/chart.jsx
  src/components/ui/checkbox.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/tabs.jsx
  src/utils/tailwind.ts
  src/utils/utils.js
Labels: Ready for Review, Typescript

#1660 config into typescript
  src/components/user/Countdown.jsx
  src/data/Config.ts
Labels: Typescript

#1662 Migrate Navigation to Shadcn Accordion
  package-lock.json
  package.json
  src/components/Navigation.jsx
  src/components/ui/accordion.jsx
  src/data/Navigation.js
Labels: Navigation, Ready for Review, Shadcn

#1555 Form sits higher
  src/components/form/form/Form.jsx
Labels: Do Not Merge, Forms, Good First Issue

#1654 Converted all react-icons to lucide-react
  cypress/component/user/Hackpack.cy.jsx
  cypress/component/user/Tile.cy.jsx
  package-lock.json
  package.json
  src/components/Loading.jsx
  src/components/Navigation.jsx
  src/components/Select.jsx
  src/components/admin/Input.jsx
  src/components/admin/Popup.jsx
  src/components/admin/dashboards/dashboard/Body.jsx
  src/components/admin/dashboards/dashboard/Filter.jsx
  src/components/admin/dashboards/dashboard/Modal.jsx
  src/components/admin/dashboards/dashboard/Table.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
  src/components/admin/services/Dropdown.jsx
  src/components/admin/services/Upload.jsx
  src/components/admin/services/calendar/Modal.jsx
  src/components/admin/services/calendar/Toolbar.jsx
  src/components/admin/services/contacts/Contact.jsx
  src/components/engineering/Landing.jsx
  src/components/engineering/Navigation.jsx
  src/components/form/form/Questions.jsx
  src/components/form/form/Textarea.jsx
  src/components/form/form/Upload.jsx
  src/components/live/faq/Item.jsx
  src/components/user/Collapse.jsx
  src/components/user/Dashboard.jsx
  src/data/Navigation.js
  src/data/admin/Icons.js
  src/data/engineering/Navigation.js
  src/data/user/Hackpacks.js
Labels: Ready for Review, Shadcn

#1567 Added textarea
  cypress/component/admin/Textarea.cy.jsx
  cypress/component/form/Textarea.cy.jsx
  src/components/admin/services/Textarea.jsx
  src/components/form/form/Questions.jsx
  src/components/form/form/Textarea.jsx
  src/components/ui/textarea.jsx
Labels: Ready for Review, Shadcn

#1670 Typescript: Dashboard Helper
  src/data/admin/Dashboard.ts
Labels: Ready for Review, Typescript

#1668 Factor Out Statuses
  cypress/component/form/Status.cy.jsx
  src/components/admin/dashboards/Admins.jsx
  src/components/admin/dashboards/Committees.jsx
  src/components/admin/dashboards/Interests.jsx
  src/components/admin/dashboards/Judges.jsx
  src/components/admin/dashboards/Leads.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Panelists.jsx
  src/components/admin/dashboards/Participants.jsx
  src/components/admin/dashboards/Sponsors.jsx
  src/components/admin/dashboards/Teams.jsx
  src/components/admin/dashboards/Volunteers.jsx
  src/components/form/Admin.jsx
  src/components/form/Committee.jsx
  src/components/form/Interest.jsx
  src/components/form/Judge.jsx
  src/components/form/Lead.jsx
  src/components/form/Mentor.jsx
  src/components/form/Panelist.jsx
  src/components/form/Participant.jsx
  src/components/form/Sponsor.jsx
  src/components/form/Volunteer.jsx
  src/data/Statuses.js
  src/data/admin/Admins.js
  src/data/admin/Committees.js
  src/data/admin/Interests.js
  src/data/admin/Judges.js
  src/data/admin/Leads.js
  src/data/admin/Mentors.js
  src/data/admin/Panelists.js
  src/data/admin/Participants.js
  src/data/admin/Sponsors.js
  src/data/admin/Teams.js
  src/data/admin/Volunteers.js
Labels: Ready for Review, Dashboards
