Repository acm-ucr/aurora, pull requests merged in 2024-05, with the labels that each got.

#1322 responsiveness
  src/components/user/Dashboard.jsx
  src/components/user/Tile.jsx
Labels: Ready for Review

#1320 changed emojis🤓🙄😡
  src/components/user/Packing.jsx
  src/components/user/Rooms.jsx
Labels: Ready for Review

#1324 fix lead application
  src/components/form/Lead.jsx
  src/data/form/Leads.js
Labels: Ready for Review, Forms

#1323 Teams Page
  src/app/user/team/page.js
  src/components/user/team/Details.jsx
  src/components/user/team/Team.jsx
Labels: Ready for Review

#1321 added hover opacity
  src/components/user/Tile.jsx
Labels: Ready for Review

#1344 center digits in user portal
  src/components/user/Countdown.jsx
Labels: Ready for Review

#1352 Fix modal background
  src/components/admin/dashboards/dashboard/Modal.jsx
Labels: Ready for Review, Bug Fix, Dashboards

#1361 made camera area larger
  src/components/admin/services/checkin/Scanner.jsx
Labels: Ready for Review

#1364 Removed duplicate instance of date in data
  src/data/Config.js
Labels: Bug Fix

#1368 added better input validation for qr code
  src/components/admin/services/checkin/CheckIn.jsx
Labels: Ready for Review, Check In

#1367 judging now fetches pending teams as well
  src/app/api/judging/route.js
Labels: Ready for Review, Judging, Backend

#1366 fix interest dashboard
  src/components/admin/dashboards/Interests.jsx
Labels: Ready for Review, Admin

#1370 Finished weird animation fixbut had to implement it in a non tailwind way
  src/components/user/Collapse.jsx
Labels: Ready for Review, Admin

#1416 Stats Mobile Responsiveness + Squares
  src/components/admin/services/statistics/Tab.jsx
  src/components/admin/services/statistics/Tabs.jsx
Labels: Ready for Review

#1414 Simplified "future marketing purposes" to "marketing purposes"
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Interest.js
  src/data/form/Judge.js
  src/data/form/Leads.js
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Participant.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Ready for Review, Forms

#1419 jefren/fixed feedback bug
  src/data/form/Feedback.js
Labels: Ready for Review, Bug Fix, Feedback

#1421 feat:Add message when no teams available (Judging)
  src/components/admin/services/judging/Judging.jsx
Labels: Ready for Review, Judging

#1422 added eventSource to interest form
  src/data/form/Interest.js
Labels: Ready for Review, Forms, Dashboards

#1426 Howard/fixing icons not displaying
  src/data/user/Hackpacks.js
Labels: Participants, Ready for Review, Hackpack

#1427 Add Majors
  src/data/form/Information.js
Labels: Participants, Ready for Review, Forms
