Repository acm-ucr/aurora, pull requests merged in 2024-08, with the labels that each got.

#1667 Fix Judging Rules
  src/data/user/Judging.jsx
Labels: User Portal

#1666 Typescript: Toaster Util
  src/utils/toaster.js
  src/utils/toaster.ts
Labels: Ready for Review, Typescript

#1570 Mailyn/resources page
  cypress/component/admin/Tab.cy.jsx
  cypress/component/user/Hackpack.cy.jsx
  src/app/loading.js
  src/app/user/resources/page.js
  src/components/admin/services/calendar/Toolbar.jsx
  src/components/admin/services/judging/Judging.jsx
  src/components/form/Admin.jsx
  src/components/form/Committee.jsx
  src/components/form/Feedback.jsx
  src/components/form/Ideas.jsx
  src/components/form/Interest.jsx
  src/components/form/Judge.jsx
  src/components/form/Lead.jsx
  src/components/form/Mentor.jsx
  src/components/form/Panelist.jsx
  src/components/form/Participant.jsx
  src/components/form/Sponsor.jsx
  src/components/form/Volunteer.jsx
  src/components/form/form/Questions.jsx
  src/components/form/form/Status.jsx
  src/components/user/CheckIn.jsx
  src/components/user/Dashboard.jsx
  src/components/user/Hackpack.jsx
  src/components/user/Hackpacks.jsx
  src/components/user/Resources.tsx
  src/components/user/resources/Hackpack.tsx
  src/components/user/resources/Resources.tsx
  src/data/Navigation.js
  src/data/user/Hackpacks.tsx
  src/data/user/Judging.ts
Labels: Do Not Merge, User Portal

#1686 typescript: loading component
  src/components/Loading.tsx
Labels: Typescript

#1685 Typescript: packing component
  src/components/user/Packing.jsx
  src/components/user/Packing.tsx
Labels: Typescript

#1684 typescript: errors component
  src/components/Error.tsx
Labels: Typescript

#1671 add types to teams api
  src/data/user/Team.ts
  src/data/user/types/types.ts
Labels: Typescript

#1646 finished judging service blog
  src/engineering/judging.mdx
Labels: Ready for Review, Engineering

#1683 Created Filter Component Test
  cypress/component/admin/Filter.cy.jsx
Labels: Ready for Review, Tests

#1652 Timer Page Implimentation
  components.json
  package-lock.json
  package.json
  src/app/admin/[type]/page.js
  src/components/admin/services/timer/Clock.jsx
  src/components/admin/services/timer/Controls.tsx
  src/components/admin/services/timer/Timer.tsx
  src/components/ui/accordion.jsx
  src/components/ui/accordion.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/components/ui/checkbox.jsx
  src/components/ui/checkbox.tsx
  src/components/ui/input-otp.tsx
  src/components/ui/input.jsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/progress.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.jsx
  src/components/ui/textarea.tsx
  src/components/user/team/Details.jsx
  src/data/Navigation.js
  src/data/admin/Judges.js
  src/utils/tailwind.ts
  tailwind.config.js
Labels: Admin, Ready to Merge

#1690 TypeScript Migrations
  src/components/Session.tsx
  src/components/admin/dashboards/Admins.jsx
  src/components/admin/dashboards/Interests.jsx
  src/components/admin/dashboards/Judges.jsx
  src/components/admin/dashboards/Leads.jsx
  src/components/admin/dashboards/Mentors.jsx
  src/components/admin/dashboards/Panelists.jsx
  src/components/admin/dashboards/Sponsors.jsx
  src/components/admin/dashboards/Teams.jsx
  src/components/admin/services/calendar/Toolbar.jsx
  src/components/form/Feedback.jsx
  src/components/form/Judge.jsx
  src/components/form/Mentor.jsx
  src/components/form/Panelist.jsx
  src/components/form/Participant.jsx
  src/components/form/Volunteer.jsx
  src/components/user/CheckIn.jsx
  src/data/Bytes.ts
  src/data/Statuses.js
  src/data/Statuses.ts
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Information.ts
  src/data/user/Team.ts
  src/types/auth.ts
  src/utils/api.ts
  src/utils/convert.ts
  src/utils/download.ts
  src/utils/error.ts
  src/utils/firebase.ts
Labels: Ready for Review

#1691 Judging Virtual Fix
  src/components/admin/services/judging/Table.jsx
Labels: Ready for Review

#1694 migrate to ts
  src/data/form/Panelists.ts
Labels: Typescript

#1695 made Icons Typescript
  src/data/admin/Icons.tsx
Labels: Admin, Typescript

#1699 integrated shadcn radio
  package-lock.json
  package.json
  src/components/form/form/Questions.jsx
  src/components/ui/radio-group.tsx
Labels: Ready for Review

#1696 Increase icon sizes
  src/components/user/Dashboard.jsx
  src/components/user/Tile.jsx
Labels: User Portal

#1702 Made to Typescript
  src/data/admin/Calendar.ts
Labels: Typescript

#1701 Add country selection to meet MLH conditions for participant signups
  cypress/fixtures/participants.json
  src/app/api/participant/route.js
  src/components/user/User.jsx
  src/data/admin/Dashboard.ts
  src/data/admin/Icons.tsx
  src/data/admin/Participants.js
  src/data/form/Countries.ts
  src/data/form/Participant.js
Labels: Ready for Review, Forms

#1693 new branch for Typescript: Mentors Dashboard
  src/components/Checkbox.tsx
  src/components/admin/dashboards/dashboard/Body.jsx
  src/components/admin/dashboards/dashboard/Table.jsx
  src/data/admin/Admins.js
  src/data/admin/Columns.js
  src/data/admin/Committees.js
  src/data/admin/Feedback.js
  src/data/admin/Interests.js
  src/data/admin/Judges.js
  src/data/admin/Leads.js
  src/data/admin/Mentors.tsx
  src/data/admin/Panelists.js
  src/data/admin/Participants.js
  src/data/admin/Sponsors.js
  src/data/admin/Teams.js
  src/data/admin/Volunteers.js
Labels: Typescript

#1704 delete messenger attempt
  src/data/admin/Messenger.js
Labels: Ready for Review

#1697 Samarth srinivasa/members type script
  src/data/user/Members.ts
  tsconfig.json
Labels: Typescript

#1553 Toolbar Responsiveness
  src/components/admin/services/judging/Toolbar.jsx
Labels: Bug Fix, Judging

#1706 Dropdown Shadcn
  cypress/component/admin/Dropdown.cy.jsx
  package-lock.json
  package.json
  src/components/Select.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
  src/components/admin/services/Dropdown.jsx
  src/components/admin/services/checkin/CheckIn.jsx
  src/components/ui/dropdown-menu.tsx
  tailwind.config.js
Labels: Ready for Review

#1700 Made Toolbar sticky
  src/components/user/schedule/Schedule.jsx
  src/components/user/schedule/Toolbar.jsx
Labels: User Portal, Calendar

#1707 fixed radio group bug
  src/components/form/form/Questions.jsx
  tsconfig.json
Labels: Ready for Review, Bug Fix

#1708 Add user portal to expand by default
  src/components/Navigation.jsx
Labels: Navigation, Ready for Review, User Portal

#1663 Add Virtualization to User Find List
  src/components/admin/services/judging/Table.jsx
  src/components/user/find/Find.jsx
  src/components/user/find/Idea.jsx
Labels: Do Not Merge, User Portal

#1712 made icons smaller
  src/components/admin/dashboards/dashboard/Table.jsx
Labels: Ready for Review

#1645 implemented shirts sizes to stats
  cypress/e2e/admin/admins/Actions.cy.js
  cypress/e2e/admin/admins/Select.cy.js
  cypress/e2e/admin/committees/Actions.cy.js
  cypress/e2e/admin/committees/Select.cy.js
  cypress/e2e/admin/interests/Actions.cy.js
  cypress/e2e/admin/interests/Select.cy.js
  cypress/e2e/admin/judges/Actions.cy.js
  cypress/e2e/admin/judges/Select.cy.js
  cypress/e2e/admin/leads/Actions.cy.js
  cypress/e2e/admin/leads/Select.cy.js
  cypress/e2e/admin/mentors/Actions.cy.js
  cypress/e2e/admin/mentors/Select.cy.js
  cypress/e2e/admin/panelists/Actions.cy.js
  cypress/e2e/admin/panelists/Select.cy.js
  cypress/e2e/admin/participants/Actions.cy.js
  cypress/e2e/admin/participants/Select.cy.js
  cypress/e2e/admin/sponsors/Actions.cy.js
  cypress/e2e/admin/sponsors/Select.cy.js
  cypress/e2e/admin/teams/Actions.cy.js
  cypress/e2e/admin/teams/Select.cy.js
  cypress/e2e/admin/volunteers/Actions.cy.js
  cypress/e2e/admin/volunteers/Select.cy.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/statistics/route.js
  src/components/admin/services/statistics/Chart.jsx
  src/components/admin/services/statistics/Charts.jsx
  src/components/admin/services/statistics/Statistics.jsx
  src/components/ui/checkbox.jsx
  src/data/admin/Statistics.js
Labels: Ready for Review

#1689 TypeScript: Leads Form
  src/data/form/Leads.ts
  src/types/forms.ts
Labels: Do Not Merge, Typescript

#1720 fixed MLH Terms & Conditions
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Interest.js
  src/data/form/Judge.js
  src/data/form/Leads.ts
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Panelists.ts
  src/data/form/Participant.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Ready for Review, Forms

#1715 Migrate admins dashboard to typescript
  src/data/admin/Admins.tsx
  src/types/dashboard.ts
Labels: Ready for Review, Typescript

#1716 Teams, Sponsors, Participants, Judges, Interests Dashboards to Typescript
  src/data/admin/Interests.tsx
  src/data/admin/Judges.tsx
  src/data/admin/Mentors.tsx
  src/data/admin/Participants.tsx
  src/data/admin/Sponsors.tsx
  src/data/admin/Teams.tsx
  src/types/dashboard.ts
Labels: Dashboards, Typescript

#1721 Made Header.jsx to .tsx
  src/components/user/Header.tsx
Labels: Typescript

#1724 Typescript: Admin Form
  src/data/form/Admins.ts
Labels: Ready for Review, Forms, Typescript

#1723 volunteers dashboard to typescript
  src/data/admin/Volunteers.tsx
Labels: Ready for Review

#1705 Update Routes
  src/data/Releases.ts
Labels: Ready for Review, Do Not Merge, Repository

#1726 Typescript: Mentors Form
  src/data/form/Mentors.ts
Labels: Forms, Typescript

#1725 Typescript: Sponsors Form
  src/data/form/Sponsors.ts
Labels: Ready for Review, Forms, Typescript

#1750 Converted stats from js to ts
  src/data/admin/Statistics.ts
Labels: Typescript

#1751 Rules
  src/data/user/Rules.ts
Labels: Ready for Review, Typescript

#1754 Amir/Change layout.js to trs
  package-lock.json
  package.json
  src/app/engineering/layout.tsx
Labels: Ready for Review, Typescript

#1753 form interest ts
  src/data/form/Interest.ts
Labels: Ready for Review

#1713 removed all start url
  src/app/manifest.js
  src/data/Config.ts
Labels: Do Not Merge

#1711 Removed Unnecessary code from Constrained Height
  src/components/admin/services/checkin/CheckIn.jsx
Labels: Do Not Merge, Bug Fix, Check In

#1758 Terms
  src/components/Checkbox.tsx
  src/components/form/form/Terms.tsx
Labels: Ready for Review, Typescript

#1755 Change Engineering Blog to ts
  src/app/engineering/blog/page.tsx
Labels: Ready for Review, Engineering, Typescript

#1763 manifest.jsx to tsx
  src/app/manifest.tsx
Labels: Ready for Review

#1761 fixed admin dashboards
  src/data/admin/Admins.tsx
  src/data/admin/Columns.js
  src/data/admin/Committees.js
  src/data/admin/Feedback.js
  src/data/admin/Judges.tsx
  src/data/admin/Leads.js
  src/data/admin/Mentors.tsx
  src/data/admin/Panelists.js
  src/data/admin/Participants.tsx
  src/data/admin/Sponsors.tsx
  src/data/admin/Teams.tsx
  src/data/admin/Volunteers.tsx
Labels: Ready for Review, Dashboards

#1757 Changed Team/page.js to ts
  src/app/user/team/page.tsx
Labels: Ready for Review, Typescript

#1766 changed file to ts
  src/app/user/schedule/page.tsx
Labels: Ready for Review, Typescript

#1764 Convert form page to Typescript
  src/app/form/[type]/page.tsx
  src/utils/error.ts
Labels: Ready for Review, Typescript

#1756 changes pg.js to ts
  src/app/engineering/hackathons/page.js
  src/app/engineering/hackathons/page.tsx
Labels: Ready for Review, Typescript

#1772 Changed page.js to tsx
  src/app/engineering/page.tsx
Labels: Ready for Review, Typescript

#1771 Changed participant.js to tsx
  src/data/user/Participant.tsx
Labels: Ready for Review, Typescript

#1768 Changed event.jsx to tsx
  src/components/admin/services/calendar/Event.tsx
Labels: Ready for Review, Typescript

#1774 change file to typescript
  src/app/auth/error/page.tsx
Labels: Ready for Review, Typescript

#1770 Changed navigation.js to tsx
  src/data/Navigation.tsx
Labels: Ready for Review, Typescript

#1777 HackathonsData type
  src/data/engineering/HackathonsData.ts
Labels: Ready for Review

#1765 TS - Hackpacks
  package-lock.json
  src/components/user/resources/Hackpack.tsx
  src/data/user/Hackpacks.tsx
Labels: Ready for Review, Typescript
