Repository acm-ucr/aurora, pull requests merged in 2024-02, with the labels that each got.

#1096 removed search bar
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready to Merge

#1094 added if empty toast
  src/components/dynamic/admin/services/contacts/Contact.jsx
Labels: Ready for Review

#1093 add phone number validation
  src/components/dynamic/Input.jsx
  src/components/dynamic/form/form/Questions.jsx
  src/components/dynamic/user/User.jsx
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Regex.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready for Review

#1097 added default resume + teams participant
  src/data/dynamic/admin/Participants.js
Labels: Ready for Review

#1095 added toast for confirming users
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review

#1092 add table number to team name for judges
  src/components/dynamic/admin/services/judging/Toolbar.jsx
Labels: Ready for Review

#1091 added more questions to admin and committees
  src/components/dynamic/admin/dashboards/Admins.jsx
  src/components/dynamic/admin/dashboards/Committees.jsx
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Dashboard.js
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
Labels: Ready for Review

#1101 added submit page
  src/components/dynamic/form/Feedback.jsx
Labels: Ready for Review, Feedback, Forms

#1024 toastUtil
  package-lock.json
  src/app/user/join/[teamID]/page.js
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
  src/components/dynamic/admin/services/Upload.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/admin/services/contacts/Contact.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
  src/components/dynamic/form/Admin.jsx
  src/components/dynamic/form/Committee.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Interest.jsx
  src/components/dynamic/form/Judge.jsx
  src/components/dynamic/form/Mentor.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Sponsor.jsx
  src/components/dynamic/form/Volunteer.jsx
  src/components/dynamic/form/form/Questions.jsx
  src/components/dynamic/form/form/Upload.jsx
  src/components/dynamic/user/Team.jsx
  src/components/dynamic/user/User.jsx
  src/utils/toaster.js
  tailwind.config.js
Labels: Ready for Review

#1119 Menthy/form
  src/components/dynamic/form/form/Questions.jsx
  src/data/dynamic/form/Judge.js
Labels: Ready for Review

#1019 Extended Next and removed react in eslint config
  .eslintrc.json
  src/app/api/dashboard/[type]/route.js
  src/app/user/join/[teamID]/page.js
  src/components/dynamic/admin/dashboards/dashboard/Modal.jsx
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
  src/components/dynamic/form/form/Form.jsx
  src/utils/email.js
Labels: Ready for Review

#1120 removed end time, moved start time to front
  src/components/dynamic/admin/services/calendar/Event.jsx
  src/components/dynamic/admin/services/calendar/Modal.jsx
Labels: Ready for Review, Calendar

#1122 Fix Pulse Animation [Front End]
  package-lock.json
  src/utils/toaster.js
Labels: Bug Fix, Repository

#1125 added calendar time limits
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: Ready for Review, Calendar, Performance

#1124 Consolidated Toaster into Singular Component
  src/utils/toaster.js
Labels: Repository

#1129 fixed cronjob to update current pr
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository

#1098 added leads application and dashboard
  src/app/admin/[type]/page.js
  src/app/api/dashboard/[type]/route.js
  src/app/form/[type]/page.js
  src/components/dynamic/admin/dashboards/Leads.jsx
  src/components/dynamic/form/Lead.jsx
  src/data/dynamic/Navigation.js
  src/data/dynamic/admin/Dashboard.js
  src/data/dynamic/admin/Icons.js
  src/data/dynamic/admin/Leads.js
  src/data/dynamic/form/Leads.js
Labels: Ready for Review, Admin, Forms, Dashboards

#1100 Images Action
  .github/workflows/pull-request.yaml
  public/UCRLOGO.png
  public/UCRLOGO.webp
Labels: Ready for Review

#1131 Make Calendar More Accessible
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: Ready for Review, Admin, Calendar

#1132 set up engineering blog
  next.config.mjs
  package-lock.json
  package.json
  src/app/engineering/[type]/page.js
  src/app/globals.css
  src/engineering/tailwind.mdx
  src/mdx-components.js
  tailwind.config.js
Labels: Ready for Review

#1155 Fixed Weekly Calendar Styling Issues
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: Repository, Calendar

#1158 Add Component Testing Engineering Blog Post
  src/app/engineering/[type]/page.js
  src/engineering/component.mdx
  src/mdx-components.js
Labels: Ready for Review

#1160 Added Devpost Link To Navbar
  src/data/Config.js
  src/data/dynamic/Navigation.js
Labels: Navigation

#1159 add settings to navigation
  src/data/dynamic/Navigation.js
Labels: Navigation

#1162 removed app export
  src/utils/firebase.js
Labels: Ready for Review, Repository

#1163 cronjob pr update fix
  .github/workflows/sync-template.yaml
Labels: Ready for Review, Repository
