Repository acm-ucr/aurora, pull requests merged in 2024-06, with the labels that each got.

#1431 added padding
  src/components/admin/services/judging/Toolbar.jsx
Labels: Ready for Review

#1432 added message variable to authentication error message
  src/app/api/settings/route.js
Labels: Ready for Review, Bug Fix

#1428 Keep Rules and Judging Open
  .eslintignore
  .gitignore
  .prettierignore
  src/components/user/BulletList.jsx
  src/components/user/Dashboard.jsx
Labels: Ready for Review, User Portal

#1417 feat:Add Shirt Size in Participants Dashboard (Admin)
  src/data/admin/Participants.js
Labels: Ready for Review, Dashboards

#1440 Width adds to 12/12 for Participants dashboard (admin)
  src/data/admin/Participants.js
Labels: Participants, Ready for Review, Admin

#1443 combined students and professors into single array
  src/components/admin/services/judging/Toolbar.jsx
Labels: Ready for Review, Bug Fix, Judging

#1444 passed meta prop as it contains total user/row count
  src/components/admin/dashboards/dashboard/Dashboard.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review, Bug Fix, Dashboards

#1442 Update lead form description
  src/data/Config.js
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Interest.js
  src/data/form/Judge.js
  src/data/form/Leads.js
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Participant.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Forms, Good First Issue

#1449 added hackpacks
  src/data/user/Hackpacks.js
Labels: User Portal

#1435 made calendar mobile repsonisve
  src/components/admin/services/calendar/Toolbar.jsx
Labels: Ready for Review

#1434 removed phone validation
  src/components/Input.jsx
  src/components/form/form/Questions.jsx
  src/components/user/User.jsx
  src/data/form/Judge.js
  src/data/form/Mentors.js
  src/data/form/Panelists.js
  src/data/form/Participant.js
  src/data/form/Regex.js
  src/data/form/Sponsors.js
  src/data/form/Volunteers.js
Labels: Ready for Review

#1452 Packing Component Test
  cypress/component/user/Packing.cy.jsx
  src/components/user/Packing.jsx
Labels: Ready for Review

#1420 Fixed Issue acm-ucr#1358: Simplify Words
  src/data/form/Information.js
Labels: Ready for Review

#1436 Radio Refactor
  cypress/component/Radio.cy.jsx
  src/components/Radio.jsx
  src/components/form/form/Questions.jsx
  src/components/user/User.jsx
Labels: Ready for Review, Refactoring

#1458 Setup Schedule Page
  package-lock.json
  src/app/user/schedule/page.js
  src/components/user/schedule/Events.jsx
  src/components/user/schedule/Schedule.jsx
  src/components/user/schedule/Toolbar.jsx
  src/data/Navigation.js
Labels: Ready to Merge

#1456 Testing confirmation message
  cypress/component/form/Confirmation.jsx
  package-lock.json
  src/components/form/form/Confirmation.jsx
Labels: Do Not Merge, Tests, Good First Issue

#1479 Make Parallel Calls
  src/app/api/judging/route.js
Labels: Ready for Review, Judging, Performance

#1453 Fixed resume
  src/components/admin/dashboards/dashboard/Modal.jsx
Labels: Ready for Review

#1482 Make Parallel Call - Changed return to await
  src/app/api/judging/route.js
Labels: Ready for Review, Bug Fix, Judging, Performance

#1481 fixed,runs in cypress
  cypress/component/form/Confirmation.cy.jsx
  src/components/form/form/Confirmation.jsx
Labels: Ready for Review

#1480 made rooms component test
  .eslintignore
  .gitignore
  .husky/pre-commit
  .prettierignore
  cypress/component/user/Rooms.cy.jsx
  package-lock.json
  src/app/robots.txt
  src/components/user/Rooms.jsx
Labels: Tests

#1489 Made the contacts suited for different devices
  src/components/admin/services/contacts/Contact.jsx
Labels: Ready for Review, Contacts

#1487 Removed UCRLOGO, kept rest of .webp's as they are used in the repo and were already updated
  public/UCRLOGO.webp
Labels: Ready for Review, Repository

#1485 Pull Request for: Fix Mobile Responsivness #1347
  package-lock.json
  package.json
  src/components/admin/dashboards/dashboard/Filter.jsx
  src/components/admin/dashboards/dashboard/Filters.jsx
  src/components/admin/dashboards/dashboard/Toolbar.jsx
Labels: Ready for Review, Ready to Merge

#1483 Created Schedule Toolbar Component
  src/components/user/schedule/Schedule.jsx
  src/components/user/schedule/Toolbar.jsx
Labels: Ready for Review, User Portal

#1461 Virtualize Judging
  src/components/admin/Popup.jsx
  src/components/admin/services/judging/Judging.jsx
  src/components/admin/services/judging/Table.jsx
  src/components/admin/services/judging/Toolbar.jsx
Labels: Ready for Review, Performance

#1491 reduced pdf file size for participants
  cypress/fixtures/participants.json
Labels: Ready for Review, Tests, Performance

#1492 Remove Dev Releases
  .husky/pre-commit
  package.json
  src/components/Release.jsx
  src/data/Releases.js
Labels: Repository, Ready to Merge

#1493 Remove Postlive
  src/app/page.js
  src/components/postlive/Postlive.jsx
  src/data/Releases.js
Labels: Repository, Ready to Merge

#1497 Setup Team Idea
  src/app/user/find/page.js
  src/components/user/find/Find.jsx
  src/components/user/find/Idea.jsx
  src/components/user/find/Toolbar.jsx
  src/data/Navigation.js
Labels: Ready to Merge

#1496 added members and discord search filters
  src/data/admin/Teams.js
Labels: Ready for Review

#1502 Abstract Affiliations Complete
  src/data/admin/Admins.js
  src/data/admin/Committees.js
  src/data/admin/Judges.js
  src/data/form/Admins.js
  src/data/form/Committees.js
  src/data/form/Information.js
Labels: Ready for Review, Ready to Merge

#1495 Created modal component test for dashboard
  cypress/component/admin/Modal.cy.jsx
  src/components/admin/dashboards/dashboard/Modal.jsx
Labels: Ready for Review, Tests

#1454 Make Parallel Calls
  package-lock.json
  package.json
  src/app/api/statistics/route.js
Labels: Statistics, Ready for Review, Performance
