Repository acm-ucr/aurora, pull requests merged in 2024-03, with the labels that each got.

#1156 add load state to dashboards
  src/components/dynamic/admin/dashboards/dashboard/Dashboard.jsx
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
Labels: Dashboards

#1165 React Virtual Blog
  src/app/engineering/[type]/page.js
  src/engineering/react-virtual.mdx
Labels: Ready for Review

#1174 fix user phone
  src/components/dynamic/user/User.jsx
Labels: Ready for Review

#1161 Eslint, prettier, and husky engineering blog
  src/app/engineering/[type]/page.js
  src/engineering/codequalityflow.mdx
Labels: Engineering

#1196 Kelly/rename sponsorship form
  package-lock.json
  src/components/dynamic/form/Sponsor.jsx
Labels: Forms, Sponsors

#1199 Calendar completed
  src/app/engineering/[type]/page.js
  src/engineering/calendar.mdx
Labels: Ready for Review, Engineering

#1198 Stormyy00/rsc calendar
  src/components/dynamic/admin/services/calendar/CalendarWrapper.jsx
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: Ready for Review

#1200 reduce checkbox spacing
  package-lock.json
  src/components/dynamic/Checkbox.jsx
Labels: Forms

#1197 shows upload failed text when an upload fails
  package-lock.json
  src/components/dynamic/form/form/Upload.jsx
Labels: Ready for Review, Forms

#1171 add toast blog
  src/app/engineering/[type]/page.js
  src/engineering/toast.mdx
Labels: Ready for Review

#1202 moved source question to the top
  src/data/dynamic/form/Feedback.js
Labels: Ready for Review, Forms

#1208 Changed dashboard link from "panels" to "panelists"
  src/data/dynamic/Navigation.js
Labels: Dashboards

#1205 enabled search on mentor and volunteer forms
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready for Review, Forms

#1206 add line breaks
  package-lock.json
  src/components/dynamic/form/Volunteer.jsx
  src/components/dynamic/form/form/Questions.jsx
Labels: Ready for Review

#1203 replaced links with icons
  src/data/dynamic/admin/Teams.js
Labels: Teams, Ready for Review

#1214 Reduce button radius x-axis
  src/components/dynamic/Button.jsx
Labels: Repository

#1217 fixed error display by adding use client
  src/app/admin/[type]/page.js
Labels: Admin

#1216 made links for website and devpost open in new tab
  src/components/dynamic/Navigation.jsx
Labels: Navigation

#1215 Add Dropdown
  src/components/dynamic/Select.jsx
  src/components/dynamic/admin/dashboards/dashboard/Dashboard.jsx
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Interests.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Leads.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Panelists.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Sponsors.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
Labels: Ready for Review, Dashboards

#1211 Compressor.js Engineering Blog
  package-lock.json
  src/app/engineering/[type]/page.js
  src/engineering/compressor.mdx
Labels: Ready for Review, Engineering

#1175 Pondohoo/next auth blog
  src/app/engineering/[type]/page.js
  src/engineering/nextauth.mdx
Labels: Ready for Review

#1218 Fix Toaster
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
  src/utils/toaster.js
Labels: Bug Fix

#1210 NextJS Blog
  src/app/engineering/[type]/page.js
  src/engineering/nextjs.mdx
Labels: Ready for Review, Engineering

#1222 added bundle analyzer
  next.config.mjs
  package-lock.json
  package.json
Labels: Ready for Review, Repository

#1224 Pagination
  cypress/support/commands.js
  package-lock.json
  src/app/admin/[type]/page.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/dashboard/feedback/route.js
  src/app/api/dashboard/teams/route.js
  src/components/dynamic/admin/dashboards/Admins.jsx
  src/components/dynamic/admin/dashboards/Committees.jsx
  src/components/dynamic/admin/dashboards/Feedback.jsx
  src/components/dynamic/admin/dashboards/Interests.jsx
  src/components/dynamic/admin/dashboards/Judges.jsx
  src/components/dynamic/admin/dashboards/Leads.jsx
  src/components/dynamic/admin/dashboards/Mentors.jsx
  src/components/dynamic/admin/dashboards/Panelists.jsx
  src/components/dynamic/admin/dashboards/Participants.jsx
  src/components/dynamic/admin/dashboards/Sponsors.jsx
  src/components/dynamic/admin/dashboards/Teams.jsx
  src/components/dynamic/admin/dashboards/Volunteers.jsx
  src/components/dynamic/admin/dashboards/dashboard/Dashboard.jsx
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
  src/components/dynamic/admin/dashboards/dashboard/Toolbar.jsx
Labels: Dashboards, Performance

#1227 create admin-dashboard
  src/app/engineering/[type]/page.js
  src/engineering/admin-dashboard.mdx
Labels: Ready for Review

#1225 tailwind engineering blog
  src/engineering/tailwind.mdx
Labels: Ready for Review, Engineering

#1229 repositioned feedback form
  package-lock.json
  src/data/dynamic/Navigation.js
Labels: Navigation, User Portal, Feedback

#1231 Added Dashboard and Services Hover Animations
  src/components/dynamic/Navigation.jsx
Labels: Ready for Review

#1099 added activity labels
  src/components/dynamic/admin/services/calendar/Toolbar.jsx
  src/data/dynamic/admin/Calendar.js
Labels: Ready for Review

#1212 Seanquiambao/bloghome
  package-lock.json
  package.json
  public/pages.webp
  public/vertical.webp
  src/app/engineering/[type]/page.js
  src/app/engineering/blog/[type]/page.js
  src/app/engineering/blog/page.js
  src/app/engineering/layout.js
  src/app/engineering/page.js
  src/app/layout.js
  src/components/dynamic/Session.jsx
  src/components/engineering/Blog.jsx
  src/components/engineering/Landing.jsx
  src/components/engineering/Navigation.jsx
  src/components/engineering/What.jsx
  src/data/engineering/Navigation.js
  src/engineering/admin-dashboard.mdx
  src/engineering/calendar.mdx
  src/engineering/codequalityflow.mdx
  src/engineering/component.mdx
  src/engineering/compressor.mdx
  src/engineering/nextauth.mdx
  src/engineering/nextjs.mdx
  src/engineering/react-virtual.mdx
  src/engineering/tailwind.mdx
  src/engineering/toast.mdx
Labels: Do Not Merge

#1230 Vertically Aligned Loading
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
Labels: Ready for Review

#1244 Setup Dashboard for More Issues
  src/components/dynamic/user/Countdown.jsx
  src/components/dynamic/user/Dashboard.jsx
  src/components/dynamic/user/Hackpack.jsx
  src/components/dynamic/user/Hackpacks.jsx
  src/components/dynamic/user/Header.jsx
  src/components/dynamic/user/Judging.jsx
  src/components/dynamic/user/Packing.jsx
  src/components/dynamic/user/Rooms.jsx
  src/components/dynamic/user/Rules.jsx
  src/components/dynamic/user/Tile.jsx
Labels: Ready for Review

#1237 Setup Hackathon Components
  src/components/engineering/hackathons/Bearhack.jsx
  src/components/engineering/hackathons/Citrushack.jsx
  src/components/engineering/hackathons/Cutiehack.jsx
  src/components/engineering/hackathons/DesignVerse.jsx
  src/components/engineering/hackathons/Hackathons.jsx
  src/components/engineering/hackathons/Rosehack.jsx
Labels: Ready for Review, Engineering

#1255 added checkin and parking buttons
  src/components/dynamic/user/Dashboard.jsx
  src/components/dynamic/user/Tile.jsx
Labels: Ready for Review, User Portal

#1256 Added opacity change to sort icons for table component on hover
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
Labels: Dashboards

#1258 created hackrooms component
  src/components/dynamic/user/Rooms.jsx
Labels: User Portal
