Repository acm-ucr/aurora, pull requests merged in 2024-10, with the labels that each got.

#1870 Protected Pages to RSC
  src/app/admin/[type]/page.js
  src/components/ProtectedPage.jsx
  src/components/SignIn.tsx
  src/components/admin/services/timer/Timer.tsx
  src/middleware.ts
Labels: Ready for Review

#1869 added missing user groups
  package-lock.json
  package.json
  src/components/admin/services/contacts/Contact.jsx
  src/components/admin/services/contacts/Contacts.tsx
Labels: Ready for Review, Contacts

#1852 changed page.js to ts
  src/app/page.tsx
  src/components/Release.tsx
  src/data/Releases.ts
Labels: Ready for Review, Typescript

#1868 Fix Search Dropdown
  src/data/admin/Admins.tsx
  src/data/admin/Feedback.tsx
  src/data/admin/Interests.tsx
  src/data/admin/Judges.tsx
  src/data/admin/Mentors.tsx
  src/data/admin/Participants.tsx
  src/data/admin/Sponsors.tsx
  src/data/admin/Teams.tsx
  src/data/admin/Volunteers.tsx
Labels: Bug Fix, Dashboards

#1874 Chairfu/add date
  src/components/user/schedule/Schedule.jsx
Labels: User Portal, Calendar

#1876 update checkout to use v4
  .github/workflows/sync-template.yaml
  src/components/ui/checkbox.tsx
Labels: Repository

#1873 changed letters
  src/data/form/Sponsors.ts
Labels: Ready for Review, Bug Fix

#1857 made dashboard RSC and typescript
  src/components/user/BulletList.jsx
  src/components/user/Dashboard.tsx
  src/components/user/DashboardWrapper.tsx
  src/components/user/Header.tsx
Labels: Ready for Review, User Portal
