Repository acm-ucr/aurora, pull requests merged in 2025-02, with the labels that each got.

#1918 Made icons on contacts consistent with the ones on sidebar
  src/components/admin/services/contacts/contact.jsx
Labels: Navigation, Good First Issue

#1929 fix sidebar trigger to show up only on nav
  src/components/protected.jsx
Labels: Forms

#1937 Dynamic routing 404 handling
  src/app/admin/[type]/page.js
  src/app/form/[type]/page.tsx
Labels: Bug Fix, Admin, Forms

#1952 Fix dashboard padding
  src/components/protected.jsx
Labels: Ready for Review

#1951 Fixed Checkbox Border
  src/components/ui/checkbox.tsx
Labels: Ready for Review

#1948 Added Padding to Button & Centered Acceptance
  src/components/form/form/status.jsx
Labels: Ready for Review

#1954 Fixed Statistic Colors
  src/components/admin/services/statistics/index.jsx
Labels: Ready for Review

#1950 Fix dropdown trigger on row
  src/components/admin/dashboards/dashboard/table.jsx
  src/data/admin/admins.tsx
  src/data/admin/committees.tsx
  src/data/admin/feedback.tsx
  src/data/admin/interests.tsx
  src/data/admin/judges.tsx
  src/data/admin/leads.tsx
  src/data/admin/mentors.tsx
  src/data/admin/panelists.js
  src/data/admin/participants.tsx
  src/data/admin/sponsors.tsx
  src/data/admin/teams.tsx
  src/data/admin/volunteers.tsx
Labels: Ready for Review, Admin, Good First Issue

#1957 Normalizing/fixing sticky header behavior
  src/app/user/schedule/page.tsx
  src/components/user/find/index.tsx
  src/components/user/resources/resources.tsx
  src/components/user/schedule/Schedule.jsx
Labels: Ready for Review

#1958 Updating Discord username character limit
  src/data/form/volunteers.ts
Labels: Ready for Review

#1956 Countdown Landing
  src/components/live/landing.tsx
  src/components/ui/countdown.tsx
  src/components/user/dashboard/countdown.tsx
Labels: Ready for Review

#1932 Team Details
  src/components/user/team/details.jsx
Labels: Ready for Review
