Repository acm-ucr/aurora, pull requests merged in 2025-04, with the labels that each got.

#1973 infinite scroll
  src/app/api/dashboard/[type]/route.js
  src/components/admin/dashboards/dashboard/dashboard.jsx
  src/components/admin/dashboards/dashboard/table.jsx
  src/components/admin/dashboards/dashboard/toolbar.jsx
  src/components/loading.tsx
  src/data/admin/admins.tsx
  src/data/admin/columns.tsx
  src/data/admin/participants.tsx
Labels: Ready for Review

#1983 add minimum height to tables
  src/components/admin/dashboards/dashboard/table.jsx
Labels: Ready for Review, Admin, Dashboards

#1982 Judge Start
  src/app/api/judging/route.js
  src/app/api/judging/start/route.js
  src/app/judge/layout.tsx
  src/app/judge/start/page.tsx
  src/components/admin/services/judging/toolbar.jsx
  src/components/judging/start/dashboard.tsx
  src/components/ui/accordion.tsx
  src/data/judge/form.ts
  src/data/judge/judge.ts
Labels: Do Not Merge

#1990 split into first and last name
  auth.d.ts
  src/app/admin/[type]/page.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/dashboard/resumes/route.js
  src/app/form/[type]/page.tsx
  src/components/admin/dashboards/panels.tsx
  src/components/form/admin.tsx
  src/components/form/committee.tsx
  src/components/form/interest.tsx
  src/components/form/judge.tsx
  src/components/form/lead.tsx
  src/components/form/mentor.tsx
  src/components/form/panel.tsx
  src/components/form/participant.tsx
  src/components/form/sponsor.tsx
  src/components/form/volunteer.tsx
  src/data/admin/admins.tsx
  src/data/admin/committees.tsx
  src/data/admin/dashboard.ts
  src/data/admin/interests.tsx
  src/data/admin/judges.tsx
  src/data/admin/leads.tsx
  src/data/admin/mentors.tsx
  src/data/admin/panelists.tsx
  src/data/admin/participants.tsx
  src/data/admin/resumes.tsx
  src/data/admin/sponsors.tsx
  src/data/admin/volunteers.tsx
  src/data/form/admins.ts
  src/data/form/committees.ts
  src/data/form/interest.ts
  src/data/form/judge.ts
  src/data/form/leads.ts
  src/data/form/mentors.ts
  src/data/form/panelists.ts
  src/data/form/participant.ts
  src/data/form/sponsors.ts
  src/data/form/volunteers.ts
  src/data/navigation.tsx
  src/schemas/admin.ts
  src/schemas/committee.ts
  src/schemas/interest.ts
  src/schemas/judge.ts
  src/schemas/lead.ts
  src/schemas/mentor.ts
  src/schemas/panel.ts
  src/schemas/participant.ts
  src/schemas/sponsor.ts
  src/schemas/volunteer.ts
  src/utils/auth.ts
Labels: Ready for Review, Backend

#1989 Results Page
  src/app/admin/[type]/page.js
  src/app/api/judging/route.js
  src/app/api/results/route.js
  src/components/admin/services/judging/table.jsx
  src/components/admin/services/results/actions.ts
  src/components/admin/services/results/index.tsx
  src/components/admin/services/results/result.tsx
  src/components/admin/services/results/rounds.tsx
  src/components/admin/services/results/teams.tsx
  src/components/judging/start/dashboard.tsx
  src/data/admin/teams.tsx
  src/data/navigation.tsx
  src/types/rounds.ts
  src/types/users.tsx
Labels: Ready for Review
